/**
 * Blind Texte — banque « Science » : retrouver la découverte, le concept ou le savant.
 *
 * Faits scientifiques rédigés dans nos propres mots.
 *
 * Format : { reponse, alias[], info (date/domaine, affichée au reveal), textes[2] }
 * textes[0] = difficile, textes[1] = facile.
 */

export const BANQUE_SCIENCE = [
  { reponse: 'La gravitation universelle', alias: ['gravitation', 'loi de la gravitation', 'newton', 'isaac newton'], info: 'Newton, 1687',
    textes: ["Une même loi explique la chute d'un objet et l'orbite de la Lune : c'est la grande unification du XVIIe siècle.",
             "L'histoire de la pomme, et la force qui attire deux masses proportionnellement à leur produit."] },
  { reponse: 'La relativité générale', alias: ['relativite generale', 'relativite', 'einstein', 'albert einstein'], info: 'Einstein, 1915',
    textes: ["Elle décrit l'attraction non comme une force, mais comme une déformation de l'espace et du temps par les masses.",
             "La théorie de 1915 confirmée quatre ans plus tard par la déviation de la lumière des étoiles pendant une éclipse."] },
  { reponse: 'L\'ADN et la double hélice', alias: ['adn', 'double helice', 'structure de l adn'], info: 'Watson, Crick et Franklin, 1953',
    textes: ["Sa structure a été déduite grâce à un cliché de diffraction pris par une chercheuse longtemps laissée dans l'ombre, Rosalind Franklin.",
             "La molécule en double hélice qui porte l'information génétique."] },
  { reponse: 'La théorie de l\'évolution', alias: ['evolution', 'darwin', 'charles darwin', 'selection naturelle'], info: 'Darwin, 1859',
    textes: ["Elle naît d'un voyage de cinq ans autour du monde et de l'observation des becs de pinsons sur un archipel du Pacifique.",
             "La sélection naturelle exposée dans « L'Origine des espèces »."] },
  { reponse: 'La pénicilline', alias: ['penicilline', 'fleming', 'alexander fleming'], info: 'Fleming, 1928',
    textes: ["Découverte grâce à une boîte de culture oubliée avant des vacances, contaminée par une moisissure qui tuait les bactéries alentour.",
             "Le premier antibiotique, issu d'un champignon du genre Penicillium."] },
  { reponse: 'La radioactivité', alias: ['radioactivite', 'marie curie', 'curie'], info: 'Becquerel et les Curie, 1896-1898',
    textes: ["Sa découvreuse la plus célèbre est la seule personne à avoir reçu des prix Nobel dans deux disciplines scientifiques différentes.",
             "Le rayonnement spontané du radium et du polonium, étudié dans un hangar de la rue Lhomond."] },
  { reponse: 'Le vaccin contre la rage', alias: ['vaccin contre la rage', 'pasteur', 'louis pasteur'], info: 'Pasteur, 1885',
    textes: ["Son inventeur, qui n'était pas médecin, a pris le risque de traiter un enfant mordu — un pari qui aurait pu le mener au tribunal.",
             "Le premier vaccin français contre une maladie mortelle transmise par morsure, testé sur le jeune Joseph Meister."] },
  { reponse: 'Le tableau périodique des éléments', alias: ['tableau periodique', 'mendeleiev', 'classification periodique'], info: 'Mendeleïev, 1869',
    textes: ["Son auteur y laissa des cases vides en prédisant les propriétés d'éléments encore inconnus — qu'on a découverts ensuite.",
             "Le tableau qui range les éléments chimiques par numéro atomique, en lignes et colonnes."] },
  { reponse: 'La mécanique quantique', alias: ['mecanique quantique', 'physique quantique', 'quantique'], info: 'années 1900-1930',
    textes: ["À son échelle, une particule n'a pas de position définie avant d'être mesurée — ce qui a fait dire à Einstein que Dieu ne joue pas aux dés.",
             "La physique de l'infiniment petit, avec ses quanta, son chat de Schrödinger et son principe d'incertitude."] },
  { reponse: 'Le Big Bang', alias: ['big bang', 'theorie du big bang'], info: 'Lemaître, 1927',
    textes: ["Formulée par un prêtre et physicien belge, elle a d'abord été baptisée ainsi par un adversaire, sur le ton de la moquerie.",
             "La théorie d'un univers en expansion depuis un état initial extrêmement dense et chaud, il y a 13,8 milliards d'années."] },
  { reponse: 'Les trous noirs', alias: ['trou noir', 'trous noirs'], info: 'photographie en 2019',
    textes: ["Leur première image directe, en 2019, a nécessité de coordonner des radiotélescopes répartis sur toute la planète.",
             "Ces objets dont la gravité est telle que même la lumière ne peut s'en échapper, bordés d'un horizon des événements."] },
  { reponse: 'L\'héliocentrisme', alias: ['heliocentrisme', 'copernic', 'nicolas copernic'], info: 'Copernic, 1543',
    textes: ["Son auteur a attendu d'être mourant pour publier, conscient de ce que son modèle allait déclencher.",
             "L'idée que la Terre tourne autour du Soleil, et non l'inverse."] },
  { reponse: 'La théorie des germes et l\'asepsie', alias: ['theorie des germes', 'asepsie', 'semmelweis', 'antisepsie'], info: 'XIXe siècle',
    textes: ["Un médecin hongrois découvre que se laver les mains entre l'amphithéâtre et la maternité fait chuter la mortalité — et se fait mettre au ban pour cela.",
             "L'idée que des micro-organismes invisibles causent les maladies, à l'origine de l'hygiène hospitalière."] },
  { reponse: 'La dérive des continents', alias: ['derive des continents', 'tectonique des plaques', 'wegener'], info: 'Wegener, 1912',
    textes: ["Proposée par un météorologue à partir de la forme des côtes et de fossiles identiques de part et d'autre d'un océan, elle fut moquée pendant cinquante ans.",
             "La théorie de la Pangée et des plaques qui bougent sous nos pieds."] },
  { reponse: 'La photosynthèse', alias: ['photosynthese'], info: 'biologie végétale',
    textes: ["C'est ce processus qui a rempli l'atmosphère terrestre d'oxygène, provoquant l'une des plus grandes extinctions de l'histoire.",
             "Comment les plantes fabriquent leur matière organique à partir de lumière, d'eau et de gaz carbonique."] },
  { reponse: 'La théorie cellulaire', alias: ['theorie cellulaire', 'cellule'], info: 'XIXe siècle',
    textes: ["Elle pose que chacune de ces unités provient forcément d'une autre — ce qui met fin à l'idée de génération spontanée.",
             "Le principe selon lequel tout être vivant est composé d'unités microscopiques, découvertes au microscope par Hooke."] },
  { reponse: 'Le génome humain', alias: ['genome humain', 'projet genome humain', 'sequencage du genome'], info: 'achevé en 2003',
    textes: ["Sa lecture complète a coûté près de trois milliards de dollars ; on refait aujourd'hui l'opération pour quelques centaines.",
             "Le séquençage des trois milliards de paires de bases de notre ADN, achevé en 2003."] },
  { reponse: 'CRISPR', alias: ['crispr', 'crispr cas9', 'ciseaux genetiques'], info: 'Charpentier et Doudna, Nobel 2020',
    textes: ["L'outil est emprunté au système immunitaire des bactéries, qui gardent en mémoire des morceaux de virus rencontrés.",
             "Les « ciseaux génétiques » qui permettent de couper l'ADN à un endroit précis, Nobel 2020."] },
  { reponse: 'Les lois de Mendel', alias: ['lois de mendel', 'mendel', 'genetique de mendel'], info: 'Mendel, 1866',
    textes: ["Ses résultats, publiés dans une revue obscure par un moine jardinier, sont restés ignorés trente-cinq ans.",
             "Les lois de l'hérédité découvertes en croisant des pois lisses et ridés."] },
  { reponse: 'La conservation de l\'énergie', alias: ['conservation de l energie', 'premier principe', 'thermodynamique'], info: 'premier principe de la thermodynamique',
    textes: ["Elle interdit définitivement le mouvement perpétuel : rien ne se crée, tout se transforme.",
             "Le principe selon lequel l'énergie totale d'un système isolé reste constante."] },
  { reponse: 'L\'entropie', alias: ['entropie', 'second principe', 'deuxieme principe'], info: 'second principe de la thermodynamique',
    textes: ["C'est la seule grandeur physique fondamentale qui donne un sens au temps : elle ne peut qu'augmenter dans un système isolé.",
             "La mesure du désordre, qui explique pourquoi la chaleur va du chaud vers le froid et jamais l'inverse."] },
  { reponse: 'La vitesse de la lumière', alias: ['vitesse de la lumiere', 'c'], info: '299 792 458 m/s',
    textes: ["Elle n'est plus mesurée mais fixée par convention : c'est elle qui définit désormais la longueur du mètre.",
             "La limite indépassable de l'univers, environ 300 000 kilomètres par seconde."] },
  { reponse: 'Le boson de Higgs', alias: ['boson de higgs', 'higgs'], info: 'CERN, 2012',
    textes: ["Sa détection a demandé un anneau de 27 kilomètres sous la frontière franco-suisse et près de cinquante ans d'attente.",
             "La particule qui explique pourquoi les autres ont une masse, confirmée en 2012."] },
  { reponse: 'Les ondes gravitationnelles', alias: ['ondes gravitationnelles', 'ligo'], info: 'LIGO, 2015',
    textes: ["Leur détection a mesuré une variation de longueur plus petite qu'un millième de la taille d'un proton.",
             "Les vibrations de l'espace-temps émises par la fusion de deux trous noirs, prédites par Einstein et observées en 2015."] },
  { reponse: 'La supraconductivité', alias: ['supraconductivite', 'supraconducteur'], info: 'Kamerlingh Onnes, 1911',
    textes: ["À très basse température, la résistance électrique de certains matériaux ne diminue pas : elle disparaît complètement.",
             "Le phénomène qui permet de faire léviter un aimant au-dessus d'un matériau refroidi à l'azote liquide."] },
  { reponse: 'Les rayons X', alias: ['rayons x', 'roentgen'], info: 'Röntgen, 1895',
    textes: ["Leur découvreur les a nommés d'après l'inconnue mathématique, faute de comprendre leur nature ; la première image montrait la main de sa femme.",
             "Le rayonnement qui traverse les tissus mous et permet la radiographie des os."] },
  { reponse: 'La table de Lavoisier et la conservation de la masse', alias: ['lavoisier', 'conservation de la masse'], info: 'Lavoisier, 1789',
    textes: ["Fondateur de la chimie moderne et fermier général, il fut guillotiné pendant la Révolution ; un juge aurait dit que la République n'avait pas besoin de savants.",
             "Le chimiste français à qui l'on doit « rien ne se perd, rien ne se crée, tout se transforme »."] },
  { reponse: 'L\'atome et son noyau', alias: ['structure de l atome', 'rutherford', 'noyau atomique', 'atome'], info: 'Rutherford, 1911',
    textes: ["L'expérience de la feuille d'or montre que quelques projectiles rebondissent : la matière est donc presque entièrement vide, avec un cœur minuscule et dense.",
             "La découverte, en 1911, qu'un corpuscule de matière est presque vide : un cœur minuscule entouré d'électrons."] },
  { reponse: 'La fission nucléaire', alias: ['fission nucleaire', 'fission'], info: 'Hahn, Meitner et Strassmann, 1938',
    textes: ["Interprétée en exil par une physicienne écartée du laboratoire à cause des lois raciales, elle fut brevetée sous le seul nom de son collègue.",
             "La rupture d'un noyau lourd d'uranium qui libère de l'énergie — principe des centrales et de la bombe A."] },
  { reponse: 'La fusion nucléaire', alias: ['fusion nucleaire', 'fusion'], info: 'physique stellaire, ITER',
    textes: ["Le réacteur international en construction dans le sud de la France vise à reproduire sur Terre ce qui se passe au cœur des étoiles.",
             "L'assemblage de noyaux légers, source de l'énergie du Soleil."] },
  { reponse: 'L\'effet de serre', alias: ['effet de serre'], info: 'Fourier, Tyndall, Arrhenius, XIXe siècle',
    textes: ["Le lien entre gaz carbonique et réchauffement a été calculé à la main par un chimiste suédois dès la fin du XIXe siècle.",
             "Le phénomène par lequel certains gaz de l'atmosphère retiennent la chaleur émise par la Terre."] },
  { reponse: 'La couche d\'ozone et le protocole de Montréal', alias: ['couche d ozone', 'trou dans la couche d ozone', 'protocole de montreal'], info: '1987',
    textes: ["C'est le cas d'école d'un problème environnemental mondial identifié, réglementé, et effectivement en voie de résolution.",
             "Le trou au-dessus de l'Antarctique, causé par les CFC des aérosols et des réfrigérateurs."] },
  { reponse: 'La machine de Turing', alias: ['machine de turing', 'turing', 'alan turing'], info: 'Turing, 1936',
    textes: ["Son concepteur a ensuite cassé un code de guerre réputé inviolable, avant d'être poursuivi pour son homosexualité.",
             "Le modèle théorique de tout ordinateur : un ruban, une tête de lecture et un jeu de règles."] },
  { reponse: 'La loi de Moore', alias: ['loi de moore', 'moore'], info: 'Gordon Moore, 1965',
    textes: ["Ce n'est pas une loi physique mais une observation empirique devenue feuille de route de toute une industrie.",
             "Le doublement régulier du nombre de transistors sur une puce."] },
  { reponse: 'L\'intelligence artificielle et les réseaux de neurones', alias: ['intelligence artificielle', 'reseaux de neurones', 'ia', 'apprentissage profond'], info: 'depuis 1943',
    textes: ["Le domaine a connu deux « hivers » de désintérêt avant que la puissance de calcul et les données massives ne le relancent.",
             "Les modèles inspirés du cerveau qui apprennent à partir d'exemples plutôt que de règles écrites."] },
  { reponse: 'Le système immunitaire et la vaccination', alias: ['vaccination', 'jenner', 'edward jenner', 'systeme immunitaire'], info: 'Jenner, 1796',
    textes: ["Le tout premier essai s'appuie sur une observation paysanne : les trayeuses ayant attrapé une maladie bénigne des vaches ne contractaient pas la variole.",
             "Le principe d'entraîner les défenses de l'organisme avec une forme atténuée d'un agent infectieux."] },
  { reponse: 'L\'éradication de la variole', alias: ['variole', 'eradication de la variole'], info: 'déclarée en 1980',
    textes: ["C'est à ce jour la seule maladie humaine officiellement disparue de la planète grâce à une campagne mondiale.",
             "La maladie déclarée éradiquée par l'OMS en 1980."] },
  { reponse: 'La circulation sanguine', alias: ['circulation sanguine', 'harvey', 'william harvey'], info: 'Harvey, 1628',
    textes: ["Sa démonstration repose sur un calcul simple : le cœur expulse en une heure plus de sang que le corps n'en contient, donc il doit tourner en boucle.",
             "La découverte que le sang circule en circuit fermé, pompé par le cœur."] },
  { reponse: 'Les neurones et le cerveau', alias: ['neurone', 'neurones', 'cajal', 'ramon y cajal'], info: 'Ramón y Cajal, fin XIXe',
    textes: ["Ses dessins à la main, réalisés au microscope, restent utilisés dans les manuels plus d'un siècle après.",
             "La démonstration que le système nerveux est fait de cellules distinctes qui communiquent entre elles."] },
  { reponse: 'Les antibiotiques et l\'antibiorésistance', alias: ['antibioresistance', 'resistance aux antibiotiques', 'antibiotiques'], info: 'enjeu de santé mondiale',
    textes: ["Le découvreur du premier d'entre eux avait lui-même averti, dès son discours Nobel, du danger d'un usage excessif.",
             "L'évolution des bactéries qui rend nos traitements progressivement inefficaces."] },
  { reponse: 'L\'ARN messager', alias: ['arn messager', 'arnm', 'vaccin a arn'], info: 'vaccins de 2020',
    textes: ["La chercheuse à l'origine de la technologie a passé des décennies sans financement, rétrogradée, avant un Nobel en 2023.",
             "La molécule qui porte l'instruction du noyau au ribosome, et la base des vaccins de 2020."] },
  { reponse: 'Les exoplanètes', alias: ['exoplanete', 'exoplanetes'], info: 'Mayor et Queloz, 1995',
    textes: ["La première autour d'une étoile semblable au Soleil fut détectée par deux Suisses, Nobel 2019 ; on en connaît aujourd'hui plus de cinq mille.",
             "Les planètes situées en dehors de notre système solaire."] },
  { reponse: 'Le télescope spatial James Webb', alias: ['james webb', 'jwst', 'telescope james webb'], info: 'lancé en décembre 2021',
    textes: ["Son miroir en nid d'abeilles dorées a dû se déplier tout seul après le lancement, en trois cents étapes sans droit à l'erreur.",
             "Le télescope infrarouge lancé en 2021, successeur de Hubble."] },
  { reponse: 'La sonde Voyager', alias: ['voyager', 'voyager 1', 'sonde voyager'], info: 'lancée en 1977',
    textes: ["Elle emporte un disque doré contenant sons et images de la Terre, à l'intention d'éventuels destinataires.",
             "La sonde lancée en 1977, premier objet humain à sortir du système solaire."] },
  { reponse: 'L\'expansion de l\'univers', alias: ['expansion de l univers', 'hubble', 'loi de hubble'], info: 'Hubble, 1929',
    textes: ["Plus une galaxie est lointaine, plus elle s'éloigne vite — et cette fuite s'accélère, pour une raison qu'on appelle faute de mieux énergie noire.",
             "La découverte que les galaxies s'éloignent les unes des autres."] },
  { reponse: 'La matière noire', alias: ['matiere noire'], info: 'Zwicky 1933, Rubin 1970',
    textes: ["Les étoiles en périphérie des galaxies tournent bien trop vite pour la masse visible : il manque environ cinq fois plus de matière qu'on n'en voit.",
             "La masse invisible qu'on déduit des effets gravitationnels sans jamais l'avoir détectée directement."] },
  { reponse: 'La théorie du chaos', alias: ['theorie du chaos', 'effet papillon', 'lorenz'], info: 'Lorenz, 1963',
    textes: ["Elle naît d'une simulation météo relancée avec trois décimales en moins, qui produit un résultat totalement différent.",
             "L'idée qu'un battement d'ailes de papillon peut déclencher une tornade à l'autre bout du monde."] },
  { reponse: 'Les fractales', alias: ['fractale', 'fractales', 'mandelbrot'], info: 'Mandelbrot, 1975',
    textes: ["Leur théoricien a commencé par se demander quelle est la longueur exacte de la côte de Bretagne — la réponse dépend de la règle utilisée.",
             "Ces figures dont chaque partie ressemble au tout, comme le flocon de Koch ou le chou romanesco."] },
  { reponse: 'Le théorème de Pythagore', alias: ['theoreme de pythagore', 'pythagore'], info: 'mathématiques',
    textes: ["Connu des Babyloniens plus de mille ans avant celui à qui on l'attribue, il compte des centaines de démonstrations différentes.",
             "Dans un triangle rectangle, le carré de l'hypoténuse est égal à la somme des carrés des deux autres côtés."] },
  { reponse: 'Le nombre Pi', alias: ['pi', 'nombre pi'], info: 'mathématiques',
    textes: ["Irrationnel et transcendant, il a été calculé à plus de cent mille milliards de décimales — sans jamais se répéter.",
             "Le rapport entre la circonférence d'un cercle et son diamètre, environ 3,14159."] },
  { reponse: 'Le zéro et les chiffres arabes', alias: ['zero', 'chiffres arabes', 'invention du zero'], info: 'Inde, Ve-VIIe siècles',
    textes: ["Venu d'Inde et transmis par les mathématiciens du monde arabe, il a mis des siècles à être accepté en Europe, où on le soupçonnait de sorcellerie.",
             "Le chiffre qui représente rien, et sans lequel la numération de position serait impossible."] },
];
