/**
 * Blind Texte — banque « Cinéma » : retrouver le film.
 *
 * Les répliques de films sont des œuvres protégées : ici, chaque scène ou moment
 * culte est DÉCRIT dans nos propres mots (contexte, situation, anecdotes de
 * tournage) — jamais cité mot à mot. C'est le principe de toute la banque intégrée.
 *
 * Format : { film, alias[], info (année/réalisateur, affichés au reveal), textes[2] }
 * textes[0] = difficile, textes[1] = facile.
 */

export const BANQUE_CINEMA = [
  { film: "L'Empire contre-attaque", alias: ['star wars 5', 'star wars v', 'empire contre attaque', 'star wars'], info: 'Irvin Kershner, 1980',
    textes: ["Sur le tournage, l'acteur masqué prononçait un faux nom de traître : la vraie phrase fut ajoutée au doublage, secret absolu.",
             "Suspendu au-dessus du vide de la Cité des Nuages, un jeune homme apprend de son pire ennemi une vérité de famille dévastatrice."] },
  { film: 'Titanic', alias: [], info: 'James Cameron, 1997',
    textes: ["Onze Oscars, et une polémique éternelle : y avait-il vraiment de la place pour deux sur cette planche ?",
             "Bras écartés à la proue du navire, elle vole au-dessus de l'océan, retenue par l'artiste qui l'a dessinée."] },
  { film: 'Le Parrain', alias: ['the godfather', 'parrain'], info: 'Francis Ford Coppola, 1972',
    textes: ["Pour jouer le patriarche, l'acteur s'était rembourré les joues de coton — un chat errant s'est invité sur ses genoux à l'image.",
             "Un producteur de cinéma récalcitrant se réveille dans son lit à côté de la tête tranchée de son cheval de course."] },
  { film: 'Pulp Fiction', alias: [], info: 'Quentin Tarantino, 1994',
    textes: ["Palme d'or 1994 : des histoires racontées dans le désordre, une montre cachée, un mystérieux contenu doré dans une mallette.",
             "Deux tueurs en costume noir débattent du nom des hamburgers à Paris, avant un twist dansé sur du Chuck Berry."] },
  { film: 'Forrest Gump', alias: [], info: 'Robert Zemeckis, 1994',
    textes: ["Assis sur un banc en Alabama, un homme simple raconte aux passants comment il a traversé toute l'histoire américaine.",
             "Sa mère comparait la vie à une boîte de chocolats ; lui a couru trois ans sans s'arrêter, barbe comprise."] },
  { film: 'Matrix', alias: ['the matrix'], info: 'Wachowski, 1999',
    textes: ["Le temps se fige, la caméra tourne autour des balles : le « bullet time » a changé le cinéma d'action.",
             "Pilule rouge ou pilule bleue : un informaticien découvre que sa réalité est une simulation contrôlée par les machines."] },
  { film: 'Inception', alias: [], info: 'Christopher Nolan, 2010',
    textes: ["Un couloir d'hôtel qui tourne sur lui-même, construit en vrai : les cascadeurs s'y battaient en apesanteur simulée.",
             "Des voleurs s'infiltrent dans les rêves, à plusieurs niveaux de profondeur — et une toupie décide de la fin, ou pas."] },
  { film: 'Le Roi Lion', alias: ['the lion king', 'roi lion'], info: 'Disney, 1994',
    textes: ["Les scénaristes le décrivaient comme « Hamlet avec des lions » ; son ouverture chantée en zoulou est reconnaissable en une note.",
             "Un lionceau est présenté à toute la savane du haut d'un rocher, avant que son oncle ne provoque une tragédie dans un canyon."] },
  { film: 'Retour vers le futur', alias: ['back to the future'], info: 'Robert Zemeckis, 1985',
    textes: ["Il faut exactement 2,21 gigowatts et 88 miles à l'heure pour que la machine du Doc fonctionne.",
             "Un lycéen remonte en 1955 à bord d'une DeLorean et doit s'assurer que ses propres parents tombent amoureux."] },
  { film: 'Jurassic Park', alias: [], info: 'Steven Spielberg, 1993',
    textes: ["Un verre d'eau qui tremble sur un tableau de bord est devenu le plan d'annonce de danger le plus imité du cinéma.",
             "Un milliardaire ouvre un parc d'attractions peuplé de dinosaures clonés — l'informaticien véreux coupe les clôtures."] },
  { film: 'E.T.', alias: ['et', 'e.t. l extra-terrestre', 'et l extraterrestre'], info: 'Steven Spielberg, 1982',
    textes: ["Sa silhouette fripée fut inspirée à la fois d'Einstein, d'un carlin et d'un poète ; il adore les bonbons.",
             "Un vélo s'envole devant la pleine lune, avec dans le panier un petit être qui veut « téléphoner maison »."] },
  { film: 'Alien', alias: ['alien le huitieme passager'], info: 'Ridley Scott, 1979',
    textes: ["Les acteurs ignoraient ce qui allait surgir du torse de leur collègue à table : leur effroi à l'écran est authentique.",
             "Dans l'espace, personne ne vous entend crier : une créature décime l'équipage du Nostromo, sauf Ripley et son chat."] },
  { film: 'Terminator 2', alias: ['terminator'], info: 'James Cameron, 1991',
    textes: ["Le méchant en métal liquide traverse les barreaux et reprend forme : une révolution d'effets numériques en 1991.",
             "Un robot venu du futur, pouce levé, s'enfonce dans le métal en fusion pour sauver l'humanité — il avait promis de revenir."] },
  { film: 'Rocky', alias: [], info: 'John G. Avildsen, 1976',
    textes: ["Son interprète, fauché, refusa de vendre son scénario sans jouer le rôle : trois Oscars plus tard, l'histoire lui a donné raison.",
             "Un boxeur de Philadelphie gravit en courant les marches d'un musée, poings levés, sur une fanfare devenue hymne."] },
  { film: 'Gladiator', alias: [], info: 'Ridley Scott, 2000',
    textes: ["Général déchu devenu esclave, il se présente dans l'arène par son vrai nom, à la barbe de l'empereur parricide.",
             "« Divertis-toi ! » : un gladiateur défie Rome entière pour venger sa famille, et retrouve les siens dans un champ de blé."] },
  { film: 'Le Seigneur des anneaux', alias: ['seigneur des anneaux', 'lord of the rings', 'la communaute de l anneau'], info: 'Peter Jackson, 2001-2003',
    textes: ["Tourné en Nouvelle-Zélande en une seule fois pour trois films ; le comédien du magicien s'est réellement cogné à une poutre.",
             "Un vieux magicien gris barre un pont souterrain à un démon de feu, bâton planté : nul ne passera."] },
  { film: 'Harry Potter', alias: ["harry potter a l'ecole des sorciers", 'harry potter 1'], info: 'Chris Columbus, 2001',
    textes: ["La voie 9¾ de King's Cross attire aujourd'hui de vraies files de touristes avec un chariot enfoncé dans le mur.",
             "Un orphelin à lunettes découvre le jour de ses 11 ans, par un géant barbu, qu'il est célèbre chez les sorciers."] },
  { film: 'Intouchables', alias: [], info: 'Nakache & Toledano, 2011',
    textes: ["Plus de 19 millions d'entrées : l'histoire vraie d'un aristocrate et de son aide à domicile de Bondy.",
             "Course-poursuite en Maserati, Earth Wind & Fire à fond : un tétraplégique fortuné embauche le candidat le moins qualifié."] },
  { film: 'Le Dîner de cons', alias: ['diner de cons'], info: 'Francis Veber, 1998',
    textes: ["Adapté d'une pièce à succès : un seul décor ou presque, un tour de reins, et des quiproquos téléphoniques en cascade.",
             "Chaque mercredi, des amis invitent à dîner un « champion » sans le lui dire ; celui-ci fait des maquettes en allumettes."] },
  { film: 'Bienvenue chez les Ch\'tis', alias: ['bienvenue chez les chtis', 'les chtis'], info: 'Dany Boon, 2008',
    textes: ["Record historique du box-office français : plus de 20 millions de spectateurs pour une mutation redoutée.",
             "Un postier provençal muté dans le Nord découvre que ni le froid ni la langue ne sont ceux qu'on lui avait promis."] },
  { film: 'Astérix et Obélix : Mission Cléopâtre', alias: ['mission cleopatre', 'asterix mission cleopatre', 'asterix et obelix'], info: 'Alain Chabat, 2002',
    textes: ["Un architecte doit bâtir un palais en trois mois sous peine de finir aux crocodiles ; heureusement, une potion existe.",
             "Numérobis, Amonbofis et un chameau qui crache : la comédie française la plus citée des dîners de famille."] },
  { film: 'OSS 117 : Le Caire, nid d\'espions', alias: ['oss 117', 'oss117'], info: 'Michel Hazanavicius, 2006',
    textes: ["Pastiche des films d'espionnage des années 50 : brushing impeccable, assurance inoxydable, diplomatie catastrophique.",
             "Un agent secret français d'une confiance aberrante sème l'incident diplomatique au Caire en croyant briller."] },
  { film: 'Les Visiteurs', alias: ['visiteurs'], info: 'Jean-Marie Poiré, 1993',
    textes: ["Un chevalier du XIIe siècle et son écuyer avalent une potion ratée et atterrissent en 1992, où tout est « okayyy ».",
             "Un noble médiéval découvre sa descendance, les voitures et la plomberie moderne, flanqué de son serf Jacquouille."] },
  { film: 'La Grande Vadrouille', alias: ['grande vadrouille'], info: 'Gérard Oury, 1966',
    textes: ["Resté 40 ans en tête du box-office français : un chef d'orchestre et un peintre en bâtiment malgré eux dans la Résistance.",
             "1942 : deux Français que tout oppose convoient des aviateurs anglais vers la zone libre, hammam et têtes de Turcs compris."] },
  { film: 'Le Fabuleux Destin d\'Amélie Poulain', alias: ['amelie poulain', 'amelie'], info: 'Jean-Pierre Jeunet, 2001',
    textes: ["Elle aime plonger la main dans les sacs de grains, faire craquer la crème brûlée et rendre les gens heureux en secret.",
             "Une serveuse de Montmartre au carré brun orchestre des bonheurs anonymes et traque un inconnu aux photomatons."] },
  { film: 'Léon', alias: ['leon'], info: 'Luc Besson, 1994',
    textes: ["Il boit du lait, soigne une plante en pot et ne dort jamais allongé ; sa voisine de douze ans va tout changer.",
             "Un tueur à gages solitaire recueille une orpheline qui veut apprendre son métier pour venger sa famille."] },
  { film: 'Le Cinquième Élément', alias: ['cinquieme element'], info: 'Luc Besson, 1997',
    textes: ["Costumes de Jean-Paul Gaultier, diva bleue à la voix impossible, et un badge multipass brandi à tout propos.",
             "Un chauffeur de taxi volant du futur voit tomber dans sa voiture une inconnue aux cheveux orange, clé du salut du monde."] },
  { film: 'Taxi', alias: [], info: 'Gérard Pirès, 1998',
    textes: ["Écrit par Luc Besson : une 406 blanche truquée qui se transforme en bolide dans les rues de Marseille.",
             "Un livreur de pizzas devenu chauffeur fou s'associe malgré lui à un policier incapable de conduire."] },
  { film: 'Shrek', alias: [], info: 'DreamWorks, 2001',
    textes: ["Premier Oscar du film d'animation de l'histoire, et une relecture moqueuse de tous les contes de fées.",
             "Un ogre vert et un âne bavard délivrent une princesse au secret nocturne, pour récupérer un marécage."] },
  { film: 'Toy Story', alias: [], info: 'Pixar, 1995',
    textes: ["Premier long-métrage entièrement en images de synthèse : quatre ans de calcul pour 81 minutes.",
             "Quand les enfants quittent la chambre, un cow-boy et un ranger de l'espace se disputent la place de jouet préféré."] },
  { film: 'Avatar', alias: [], info: 'James Cameron, 2009',
    textes: ["Plus gros succès de l'histoire du box-office : douze ans de développement pour une planète phosphorescente.",
             "Un marine paraplégique pilote un corps bleu de trois mètres et choisit le camp du peuple qu'il devait trahir."] },
  { film: 'Avengers', alias: ['the avengers'], info: 'Joss Whedon, 2012',
    textes: ["Six héros qui ne se supportent pas, un plan tournant à 360° dans New York dévastée, et un dieu jeté comme une poupée.",
             "Un milliardaire en armure, un soldat décongelé, un dieu nordique et un colosse vert défendent New York d'une invasion."] },
  { film: 'The Dark Knight', alias: ['dark knight', 'batman the dark knight', 'le chevalier noir'], info: 'Christopher Nolan, 2008',
    textes: ["Son antagoniste au maquillage craquelé improvisa des applaudissements lents en cellule ; l'acteur reçut un Oscar posthume.",
             "Un clown anarchiste brûle une montagne de billets et force Gotham à des choix impossibles entre deux ferrys."] },
  { film: 'Fight Club', alias: [], info: 'David Fincher, 1999',
    textes: ["Un narrateur insomniaque, du savon artisanal, et une première règle célèbre : ne pas en parler.",
             "Des hommes se battent en sous-sol à mains nues autour d'un vendeur de savon charismatique — le twist final est légendaire."] },
  { film: 'Seven', alias: ['se7en'], info: 'David Fincher, 1995',
    textes: ["Sept jours, sept crimes calqués sur les péchés capitaux, et un colis livré en plein désert au dénouement.",
             "Deux inspecteurs traquent un tueur méthodique qui punit la gourmandise, l'avarice, la paresse… jusqu'à la colère."] },
  { film: 'Usual Suspects', alias: ['the usual suspects'], info: 'Bryan Singer, 1995',
    textes: ["Tout le film tient dans un interrogatoire — et dans les objets punaisés au mur derrière l'inspecteur.",
             "Un escroc boiteux raconte l'histoire d'un criminel mythique que personne n'a jamais vu : Keyser Söze."] },
  { film: 'Shining', alias: ['the shining'], info: 'Stanley Kubrick, 1980',
    textes: ["La scène de la porte défoncée à la hache demanda des dizaines de prises ; l'actrice était à bout de nerfs, à dessein.",
             "Gardien d'hiver d'un hôtel isolé, un écrivain tape mille fois la même phrase avant de traquer sa famille, hache en main."] },
  { film: 'Psychose', alias: ['psycho'], info: 'Alfred Hitchcock, 1960',
    textes: ["Le réalisateur acheta tous les exemplaires du roman pour préserver le twist, et interdit l'entrée après le début des séances.",
             "Une automobiliste en fuite s'arrête dans un motel tenu par un jeune homme très attaché à sa mère ; la douche est fatale."] },
  { film: 'Le Silence des agneaux', alias: ['silence des agneaux'], info: 'Jonathan Demme, 1991',
    textes: ["Cinq Oscars majeurs pour à peine 16 minutes d'écran de son antagoniste — un record d'efficacité glaçante.",
             "Une jeune recrue du FBI consulte en prison un psychiatre cannibale raffiné pour traquer un autre tueur."] },
  { film: 'Dirty Dancing', alias: [], info: 'Emile Ardolino, 1987',
    textes: ["Le porté final au-dessus de la piste est devenu l'exercice le plus périlleux des mariages du monde entier.",
             "Été 1963 : la fille d'un médecin apprend la danse — et la vie — avec le professeur de l'hôtel, qu'on ne met pas dans un coin."] },
  { film: 'Ghost', alias: [], info: 'Jerry Zucker, 1990',
    textes: ["Une médium escroc découvre avec effroi qu'elle entend réellement les morts — Oscar pour Whoopi Goldberg.",
             "Un tour de potier à deux, sur Unchained Melody : l'amour continue par-delà la mort, pour protéger celle qui reste."] },
  { film: 'Star Wars : Un nouvel espoir', alias: ['star wars 4', 'la guerre des etoiles', 'un nouvel espoir', 'star wars iv'], info: 'George Lucas, 1977',
    textes: ["Le studio n'y croyait pas ; le réalisateur négocia les produits dérivés à la place d'un salaire. Erreur historique du studio.",
             "Une princesse cache des plans dans un petit droïde ; un fermier découvre un sabre laser et une force mystérieuse."] },
  { film: 'Indiana Jones : Les Aventuriers de l\'arche perdue', alias: ['indiana jones', 'les aventuriers de l arche perdue'], info: 'Steven Spielberg, 1981',
    textes: ["Malade le jour du tournage, l'acteur régla un duel au sabre d'un simple geste las — la scène improvisée est restée culte.",
             "Un archéologue au fouet et au chapeau fuit une boulle de pierre géante, et déteste par-dessus tout les serpents."] },
  { film: 'Les Bronzés font du ski', alias: ['les bronzes font du ski', 'les bronzes'], info: 'Patrice Leconte, 1979',
    textes: ["La troupe du Splendid transforme des vacances aux sports d'hiver en anthologie de répliques pour repas de famille.",
             "Planté dans la poudreuse ou buvant une liqueur de crapaud chez des montagnards, Jean-Claude Dusse espère toujours « conclure »."] },
  { film: 'La Cité de la peur', alias: ['cite de la peur'], info: 'Alain Berbérian / Les Nuls, 1994',
    textes: ["Un tueur élimine les projectionnistes d'un navet d'horreur pendant le festival de Cannes ; une carioca s'ensuit.",
             "Odile Deray, attachée de presse, et Serge Karamazov, garde du corps : la comédie culte des Nuls."] },
];
