/**
 * Blind Texte — banque « Sport » : retrouver l'exploit, l'athlète ou la compétition.
 *
 * Faits sportifs rédigés dans nos propres mots.
 *
 * RÈGLE D'OR : un texte ne doit JAMAIS contenir sa propre réponse ni un alias.
 * Format : { reponse, alias[], info, textes[2] } — textes[0] difficile, [1] facile.
 */

export const BANQUE_SPORT = [
  { reponse: 'La Coupe du monde 1998', alias: ['france 98', 'mondial 98', 'coupe du monde 1998'], info: '12 juillet 1998, Saint-Denis',
    textes: ["Un défenseur central inscrit deux buts de la tête sur corner en finale, lui qui n'en avait jamais marqué en sélection.",
             "3-0 contre le Brésil au Stade de France : la première étoile des Bleus."] },
  { reponse: 'La Coupe du monde 2018', alias: ['mondial 2018', 'coupe du monde 2018', 'russie 2018'], info: '15 juillet 2018, Moscou',
    textes: ["Une finale à six buts sous la pluie, avec le premier but contre son camp de l'histoire des finales.",
             "4-2 contre la Croatie : la deuxième étoile, vingt ans après la première."] },
  { reponse: 'La main de Dieu de Maradona', alias: ['main de dieu', 'maradona'], info: 'Mexique, 22 juin 1986',
    textes: ["Quatre minutes après un but irrégulier de la main, le même joueur en marque un autre en dribblant la moitié de l'équipe adverse.",
             "Le but au poing contre l'Angleterre en 1986, suivi du « but du siècle »."] },
  { reponse: 'Le coup de tête de Zidane', alias: ['coup de tete de zidane', 'zidane materazzi', 'finale 2006'], info: 'Berlin, 9 juillet 2006',
    textes: ["Dernier match d'une carrière immense, terminé par un carton rouge à la 110ᵉ minute après une insulte.",
             "Le geste sur Materazzi en finale de Coupe du monde 2006."] },
  { reponse: 'Michael Jordan', alias: ['jordan', 'mj'], info: 'Chicago Bulls, 6 titres NBA',
    textes: ["Recalé de l'équipe première de son lycée, il a remporté six titres majeurs en deux séries de trois, séparées par une retraite au baseball.",
             "Le numéro 23 des Bulls, sa langue tirée et son « Flu Game »."] },
  { reponse: 'Usain Bolt', alias: ['bolt'], info: 'Berlin 2009 : 9″58',
    textes: ["Il détient encore les records du monde du 100 et du 200 mètres, établis lors des mêmes championnats en 2009.",
             "Le Jamaïcain à la pose de l'archer, triple champion olympique du sprint."] },
  { reponse: 'Les Jeux olympiques de Berlin 1936', alias: ['jo 1936', 'berlin 1936', 'jeux olympiques de berlin'], info: 'août 1936',
    textes: ["Un athlète afro-américain y remporte quatre médailles d'or, ruinant la démonstration que le régime hôte voulait organiser.",
             "Les Jeux de Jesse Owens sous le régime nazi."] },
  { reponse: 'Le Tour de France', alias: ['tour de france'], info: 'depuis 1903',
    textes: ["Créé pour vendre un journal sportif, il a donné à son leader une tunique de la couleur du papier de ce journal.",
             "La grande boucle cycliste de trois semaines et son maillot jaune."] },
  { reponse: 'Eddy Merckx', alias: ['merckx'], info: 'cyclisme, 1965-1978',
    textes: ["Surnommé « le Cannibale » parce qu'il ne laissait rien aux autres, il a gagné 525 courses professionnelles.",
             "Le Belge quintuple vainqueur du Tour de France, considéré comme le plus grand cycliste de l'histoire."] },
  { reponse: 'Roland-Garros', alias: ['roland garros'], info: 'Paris, depuis 1928',
    textes: ["Seul tournoi majeur de son sport disputé sur terre battue, il porte le nom d'un aviateur.",
             "Le tournoi du Grand Chelem parisien, sur ocre."] },
  { reponse: 'Rafael Nadal', alias: ['nadal', 'rafa'], info: '14 titres à Roland-Garros',
    textes: ["Gaucher contrarié — il jouait à droite enfant —, il a gagné quatorze fois le même tournoi majeur.",
             "Le « roi de la terre battue » espagnol, aux rituels obsessionnels avec ses bouteilles."] },
  { reponse: 'Roger Federer', alias: ['federer'], info: '20 titres du Grand Chelem',
    textes: ["Son revers à une main et sa fluidité ont fait dire à des adversaires qu'il jouait un autre sport.",
             "Le Suisse octuple vainqueur de Wimbledon."] },
  { reponse: 'Wimbledon', alias: [], info: 'Londres, depuis 1877',
    textes: ["Tenue blanche obligatoire, fraises à la crème et un gazon tondu à huit millimètres exactement.",
             "Le plus ancien tournoi de tennis du monde, sur herbe, dans la banlieue londonienne."] },
  { reponse: 'Muhammad Ali', alias: ['ali', 'cassius clay'], info: 'boxe, 1960-1981',
    textes: ["Déchu de son titre pour avoir refusé d'aller à la guerre, il l'a reconquis sept ans plus tard en épuisant son adversaire dos aux cordes à Kinshasa.",
             "Le boxeur qui volait comme un papillon et piquait comme une abeille."] },
  { reponse: 'Le Mans 24 heures', alias: ['24 heures du mans', '24h du mans', 'les 24 heures du mans'], info: 'depuis 1923',
    textes: ["L'épreuve la plus meurtrière de l'histoire du sport automobile s'y est produite en 1955, avec plus de quatre-vingts spectateurs tués.",
             "La course d'endurance sarthoise où l'on roule un jour entier, avec sa ligne droite des Hunaudières."] },
  { reponse: 'Ayrton Senna', alias: ['senna'], info: 'Formule 1, 1984-1994',
    textes: ["Sa rivalité avec un coéquipier français a marqué la fin des années 80 ; il est mort en course à Imola en 1994.",
             "Le Brésilien triple champion du monde de Formule 1, maître de la conduite sous la pluie."] },
  { reponse: 'Michael Schumacher', alias: ['schumacher', 'schumi'], info: '7 titres de champion du monde',
    textes: ["Il a gagné cinq titres d'affilée avec une écurie italienne qui n'en avait plus remporté depuis vingt et un ans.",
             "L'Allemand aux sept couronnes mondiales de Formule 1, victime d'un accident de ski en 2013."] },
  { reponse: 'Le Ballon d\'or', alias: ['ballon d or'], info: 'créé en 1956',
    textes: ["Distinction créée par un magazine français, longtemps réservée aux joueurs européens avant son ouverture au monde entier.",
             "Le trophée individuel annuel du meilleur footballeur, remporté huit fois par Lionel Messi."] },
  { reponse: 'Pelé', alias: ['pele', 'edson arantes do nascimento'], info: '3 Coupes du monde',
    textes: ["Il est le seul joueur à avoir remporté trois fois le trophée mondial, dont le premier à dix-sept ans.",
             "Le Brésilien au numéro 10, déclaré trésor national pour l'empêcher d'être transféré."] },
  { reponse: 'Le Grand Chelem au rugby', alias: ['grand chelem rugby', 'tournoi des six nations', 'six nations'], info: 'Tournoi des Six Nations',
    textes: ["Réaliser cet exploit signifie battre toutes les autres nations de la compétition dans la même édition.",
             "Gagner tous ses matchs du Tournoi européen annuel de rugby, avec la cuillère de bois pour le dernier."] },
  { reponse: 'La Coupe du monde de rugby 1995', alias: ['coupe du monde de rugby 1995', 'mondial rugby 1995'], info: 'Afrique du Sud, 24 juin 1995',
    textes: ["Un président fraîchement élu remet le trophée en portant le maillot de l'équipe longtemps symbole de la ségrégation.",
             "Mandela, le maillot n°6 et la victoire des Springboks à Johannesburg."] },
  { reponse: 'Le marathon', alias: ['marathon'], info: '42,195 km',
    textes: ["Sa distance exacte a été fixée en 1908 à Londres pour que l'arrivée se trouve devant la loge royale.",
             "La course à pied de 42,195 km, inspirée d'un messager grec."] },
  { reponse: 'Les Jeux olympiques antiques', alias: ['jeux olympiques antiques', 'jeux d olympie'], info: 'à partir de 776 av. J.-C.',
    textes: ["On suspendait les guerres pendant leur durée, et les athlètes concouraient nus, enduits d'huile, en l'honneur de Zeus.",
             "Les compétitions sportives grecques disputées tous les quatre ans dans l'Antiquité, ancêtres des Jeux modernes."] },
  { reponse: 'Le Super Bowl', alias: ['super bowl'], info: 'finale de la NFL',
    textes: ["Son spectacle de mi-temps et ses écrans publicitaires coûtent plus cher que bien des championnats entiers.",
             "La finale annuelle du football américain."] },
  { reponse: 'La NBA', alias: ['nba'], info: 'fondée en 1946',
    textes: ["Sa ligne à trois points n'a été introduite qu'en 1979, après avoir été testée dans une ligue rivale.",
             "Le championnat nord-américain de basket-ball."] },
  { reponse: 'Kobe Bryant', alias: ['kobe'], info: 'Los Angeles Lakers, 1996-2016',
    textes: ["Il a inscrit 81 points en un seul match en 2006, deuxième total de l'histoire de sa ligue.",
             "Le « Black Mamba » des Lakers, disparu dans un accident d'hélicoptère en 2020."] },
  { reponse: 'Le Tour de France de Jacques Anquetil et Raymond Poulidor', alias: ['anquetil poulidor', 'poulidor', 'anquetil'], info: 'Puy de Dôme, 1964',
    textes: ["Deux rivaux montent épaule contre épaule un volcan auvergnat ; l'éternel second ne gagnera jamais la course mais restera le plus aimé.",
             "Le duel au coude à coude sur le Puy de Dôme en 1964, entre le maître et l'éternel deuxième."] },
  { reponse: 'Les Jeux paralympiques', alias: ['jeux paralympiques', 'paralympiques'], info: 'depuis Rome 1960',
    textes: ["Nés d'une compétition organisée dans un hôpital britannique pour des blessés de guerre le jour de l'ouverture des Jeux de Londres 1948.",
             "La compétition internationale des athlètes handisport, organisée après les Jeux olympiques."] },
  { reponse: 'Le Trophée Jules Rimet', alias: ['jules rimet', 'trophee jules rimet'], info: 'volé en 1983',
    textes: ["Caché sous un lit pendant la Seconde Guerre mondiale, volé deux fois, il a fini fondu par ses ravisseurs.",
             "Le premier trophée de la Coupe du monde de football, définitivement acquis par le Brésil en 1970."] },
  { reponse: 'Le judo', alias: [], info: 'créé par Jigoro Kano, 1882',
    textes: ["Sa devise tient en une formule : céder pour vaincre, utiliser la force de l'adversaire contre lui.",
             "L'art martial japonais des ceintures de couleur, où l'on marque ippon."] },
  { reponse: 'Teddy Riner', alias: ['riner'], info: '11 titres mondiaux',
    textes: ["Il a enchaîné 154 combats sans défaite entre 2010 et 2020, un record sans équivalent dans son sport.",
             "Le judoka guadeloupéen, décuple champion du monde des lourds."] },
  { reponse: 'Les Jeux olympiques de Paris 2024', alias: ['paris 2024', 'jo 2024', 'jo de paris'], info: 'juillet-août 2024',
    textes: ["Sa cérémonie d'ouverture s'est déroulée sur un fleuve plutôt que dans un stade, une première.",
             "Les Jeux d'été organisés en France cent ans après les précédents."] },
  { reponse: 'Le Trophée des Champions de la Ligue des champions', alias: ['ligue des champions', 'champions league', 'coupe d europe'], info: 'UEFA, depuis 1955',
    textes: ["Un club madrilène en a remporté les cinq premières éditions d'affilée, et en compte aujourd'hui plus du double.",
             "La plus prestigieuse compétition européenne de clubs de football, aux oreilles bien connues."] },
  { reponse: 'Le doublé de Jesse Owens', alias: ['jesse owens', 'owens'], info: 'Berlin 1936, 4 médailles d\'or',
    textes: ["Un concurrent allemand lui a discrètement donné un conseil technique pendant le concours de saut, geste resté célèbre.",
             "Le sprinteur américain aux quatre titres olympiques de 1936."] },
  { reponse: 'Simone Biles', alias: ['biles'], info: 'gymnastique artistique',
    textes: ["Quatre figures portent son nom au code de pointage, et son retrait pour raisons de santé mentale en 2021 a marqué un tournant.",
             "La gymnaste américaine la plus titrée de l'histoire."] },
  { reponse: 'Michael Phelps', alias: ['phelps'], info: '23 titres olympiques',
    textes: ["Il détient le record absolu de médailles d'or aux Jeux, tous sports et toutes époques confondus.",
             "Le nageur américain aux huit titres lors des seuls Jeux de Pékin 2008."] },
  { reponse: 'Le Ski alpin et la Coupe du monde', alias: ['ski alpin', 'coupe du monde de ski'], info: 'depuis 1967',
    textes: ["Les disciplines vont de la descente, à plus de 140 km/h, au slalom aux portes très rapprochées.",
             "Le circuit hivernal des skieurs et son gros globe de cristal."] },
  { reponse: 'Le Ballon rond de la Coupe d\'Afrique des nations', alias: ['can', 'coupe d afrique des nations', 'coupe d afrique'], info: 'depuis 1957',
    textes: ["Sa tenue en janvier a longtemps créé des conflits avec les clubs européens qui perdaient leurs joueurs en pleine saison.",
             "Le championnat continental africain de football."] },
  { reponse: 'Le Vendée Globe', alias: ['vendee globe'], info: 'depuis 1989',
    textes: ["Un tour du monde à la voile, sans escale et sans assistance, réputé le défi le plus dur de la navigation en solitaire.",
             "La course au large qui part des Sables-d'Olonne tous les quatre ans."] },
  { reponse: 'Le Dakar', alias: ['rallye dakar', 'paris dakar', 'dakar'], info: 'depuis 1979',
    textes: ["Créé après qu'un motard se soit perdu dans le désert libyen, il a quitté l'Afrique en 2009 pour raisons de sécurité.",
             "Le rallye-raid de janvier, longtemps couru entre la France et le Sénégal."] },
  { reponse: 'Le Tournoi de Roland-Garros de Yannick Noah', alias: ['yannick noah', 'noah 1983'], info: '5 juin 1983',
    textes: ["Aucun joueur de son pays n'a gagné ce tournoi majeur à domicile depuis — plus de quarante ans d'attente.",
             "Le dernier Français vainqueur en simple à Paris, en 1983, qui saute dans les bras de son père."] },
  { reponse: 'La boxe de George Foreman et le Rumble in the Jungle', alias: ['rumble in the jungle', 'foreman', 'george foreman'], info: 'Kinshasa, 30 octobre 1974',
    textes: ["Le champion en titre, réputé invincible, s'épuise à frapper un adversaire qui reste volontairement adossé aux cordes.",
             "Le combat de Kinshasa en 1974, gagné par Mohamed Ali au huitième round."] },
  { reponse: 'Le Handball français et les Experts', alias: ['les experts', 'handball francais', 'equipe de france de handball'], info: 'années 2000-2010',
    textes: ["Cette génération a réussi le grand chelem : championne olympique, mondiale et européenne en même temps.",
             "La sélection tricolore de hand des frères Karabatic, surnommée d'après une série télévisée."] },
  { reponse: 'Le Cricket et les Ashes', alias: ['ashes', 'the ashes', 'cricket'], info: 'Angleterre-Australie, depuis 1882',
    textes: ["Le trophée en jeu est une minuscule urne contenant les cendres d'un piquet brûlé après une défaite humiliante.",
             "La série de test-matchs entre Anglais et Australiens dans ce sport de battes et de guichets."] },
  { reponse: 'Le Sumo', alias: ['sumo'], info: 'Japon',
    textes: ["Les combattants vivent en écuries selon des règles très strictes, et le rang suprême ne peut être retiré : on doit démissionner.",
             "La lutte japonaise où il faut sortir l'adversaire du cercle, pratiquée par des yokozuna."] },
  { reponse: 'Le Ballon ovale et la Nouvelle-Zélande', alias: ['all blacks', 'nouvelle zelande rugby', 'haka'], info: 'rugby à XV',
    textes: ["Avant chaque match, l'équipe exécute une danse rituelle maorie destinée à défier l'adversaire.",
             "L'équipe néo-zélandaise en noir, la plus titrée de l'histoire du rugby."] },
  { reponse: 'Le Tour d\'Italie', alias: ['giro', 'tour d italie', 'giro d italia'], info: 'depuis 1909',
    textes: ["Son leader porte du rose, couleur du papier du journal qui l'a créé.",
             "Le grand tour cycliste transalpin de mai, avec ses cols des Dolomites."] },
  { reponse: 'Le Football américain universitaire et Tom Brady', alias: ['tom brady', 'brady'], info: '7 Super Bowls',
    textes: ["Sélectionné en 199ᵉ position d'une draft, il a fini avec plus de bagues de champion que n'importe quelle franchise entière.",
             "Le quarterback américain aux sept titres, joueur jusqu'à 45 ans."] },
  { reponse: 'L\'escalade et Alex Honnold', alias: ['alex honnold', 'honnold', 'free solo'], info: 'El Capitan, 3 juin 2017',
    textes: ["Il a gravi une paroi de près de mille mètres sans corde ni assurance, exploit filmé et récompensé d'un Oscar.",
             "Le grimpeur américain de l'ascension en solo intégral d'El Capitan."] },
  { reponse: 'La Coupe Davis', alias: ['coupe davis'], info: 'tennis par équipes, depuis 1900',
    textes: ["Compétition par nations où l'on joue à domicile sur la surface de son choix, ce qui donne des choix tactiques radicaux.",
             "Le « saladier d'argent » du tennis masculin par équipes."] },
];
