/**
 * Blind Texte — banque « Séries » : retrouver la série.
 *
 * Comme partout dans la banque intégrée : aucune réplique citée mot à mot.
 * Chaque manche décrit une intrigue, un personnage ou un moment marquant avec
 * nos propres mots. Les titres et les faits de production sont factuels.
 *
 * Format : { serie, alias[], info (chaîne/années, affichée au reveal), textes[2] }
 * textes[0] = difficile, textes[1] = facile.
 */

export const BANQUE_SERIES = [
  { serie: 'Breaking Bad', alias: [], info: 'AMC, 2008-2013',
    textes: ["Un professeur de chimie de lycée, diagnostiqué d'un cancer, décide d'assurer l'avenir financier de sa famille par des moyens très illégaux.",
             "Un camping-car dans le désert du Nouveau-Mexique, un chapeau noir et un alias : Heisenberg."] },
  { serie: 'Game of Thrones', alias: ['le trone de fer', 'got'], info: 'HBO, 2011-2019',
    textes: ["Adaptée de romans inachevés, elle a fini par dépasser son auteur — et sa dernière saison reste un sujet de dispute.",
             "Sept royaumes se déchirent pour un trône de lames fondues, pendant que l'hiver et les morts avancent depuis le Nord."] },
  { serie: 'Friends', alias: [], info: 'NBC, 1994-2004',
    textes: ["Six amis new-yorkais, un canapé orange dans un café, et un générique où l'on tape dans ses mains.",
             "Ross, Rachel, Monica, Chandler, Joey et Phoebe : la sitcom des années 90 par excellence."] },
  { serie: 'The Office', alias: ['the office us'], info: 'NBC, 2005-2013 (version américaine)',
    textes: ["Faux documentaire : les employés d'une papeterie de Pennsylvanie regardent la caméra quand leur patron dépasse les bornes.",
             "Michael Scott, Dwight, et une histoire d'amour entre un commercial et la réceptionniste, Jim et Pam."] },
  { serie: 'Stranger Things', alias: [], info: 'Netflix, depuis 2016',
    textes: ["Hommage aux années 80 : des gamins à vélo, des talkies-walkies, et un laboratoire gouvernemental qui a ouvert une porte.",
             "Une fillette au crâne rasé aux pouvoirs télékinésiques, le Monde à l'Envers, et un Démogorgon à Hawkins."] },
  { serie: 'La Casa de Papel', alias: ['casa de papel', 'money heist'], info: 'Antena 3 / Netflix, 2017-2021',
    textes: ["Des braqueurs en combinaison rouge et masque de Dalí impriment eux-mêmes des billets à la Fabrique nationale de la monnaie.",
             "Le Professeur, Tokyo, Berlin, Nairobi : un braquage espagnol devenu phénomène mondial sur fond de « Bella Ciao »."] },
  { serie: 'Squid Game', alias: [], info: 'Netflix, depuis 2021',
    textes: ["Des surendettés acceptent des jeux d'enfants coréens où perdre signifie mourir, sous l'œil de gardes masqués.",
             "Combinaisons vertes, poupée géante qui compte, et biscuits en sucre à découper : le carton coréen de 2021."] },
  { serie: 'Peaky Blinders', alias: [], info: 'BBC, 2013-2022',
    textes: ["Birmingham après la Grande Guerre : une famille de gitans irlandais monte des paris truqués et des trafics d'armes.",
             "Des casquettes à lame de rasoir, Tommy Shelby, et une famille qui règne sur Birmingham dans les années 1920."] },
  { serie: 'The Walking Dead', alias: ['walking dead'], info: 'AMC, 2010-2022',
    textes: ["Un shérif se réveille d'un coma dans un hôpital désert : le monde a basculé pendant son sommeil.",
             "Des survivants errent en Géorgie face à des morts-vivants qu'ils appellent des « rôdeurs »."] },
  { serie: 'Dexter', alias: [], info: 'Showtime, 2006-2013',
    textes: ["Le jour, il analyse les traces de sang pour la police de Miami. La nuit, il applique un code hérité de son père adoptif.",
             "Un expert médico-légal de Miami est aussi un tueur en série… qui ne tue que d'autres tueurs."] },
  { serie: 'Lost', alias: ['les disparus'], info: 'ABC, 2004-2010',
    textes: ["Après un crash aérien, les rescapés découvrent une trappe, des chiffres obsédants et des habitants qu'ils appellent « les Autres ».",
             "Des survivants d'un vol Sydney-Los Angeles échouent sur une île qui n'a rien de normal."] },
  { serie: 'Sherlock', alias: [], info: 'BBC, 2010-2017',
    textes: ["Le détective victorien transposé au XXIe siècle : SMS affichés à l'écran, blog du docteur, et un palais mental.",
             "Benedict Cumberbatch et Martin Freeman revisitent Holmes et Watson dans le Londres moderne."] },
  { serie: 'House of Cards', alias: [], info: 'Netflix, 2013-2018',
    textes: ["Un élu ambitieux commente ses manœuvres en s'adressant directement au spectateur, face caméra.",
             "Frank Underwood gravit un à un les échelons du pouvoir à Washington, sans le moindre scrupule."] },
  { serie: 'Black Mirror', alias: [], info: 'Channel 4 / Netflix, depuis 2011',
    textes: ["Anthologie : chaque épisode est une histoire indépendante sur ce que la technologie fait de nous.",
             "Notes sociales, souvenirs enregistrés, abeilles-drones : la série d'anticipation la plus pessimiste sur nos écrans."] },
  { serie: 'Chernobyl', alias: ['tchernobyl'], info: 'HBO, 2019',
    textes: ["Mini-série en cinq épisodes sur une catastrophe de 1986, saluée pour sa reconstitution glaçante et son procès final.",
             "Le réacteur n°4, les liquidateurs, et un dosimètre qui affiche l'impossible en Ukraine soviétique."] },
  { serie: 'The Mandalorian', alias: ['mandalorian'], info: 'Disney+, depuis 2019',
    textes: ["Un chasseur de primes casqué, tenu par un code qui lui interdit de montrer son visage, accepte un contrat qu'il trahit aussitôt.",
             "Un guerrier en armure de beskar protège un enfant vert aux grandes oreilles, surnommé Bébé Yoda."] },
  { serie: 'The Crown', alias: [], info: 'Netflix, 2016-2023',
    textes: ["Chaque saison change de distribution pour suivre le vieillissement des personnages sur plusieurs décennies.",
             "La chronique romancée du règne d'Élisabeth II, de son couronnement aux crises de la famille royale."] },
  { serie: 'Better Call Saul', alias: [], info: 'AMC, 2015-2022',
    textes: ["Préquelle d'une série culte : on y suit un avocat magouilleur avant qu'il ne change de nom pour attirer les criminels.",
             "Comment Jimmy McGill est devenu l'avocat véreux de Breaking Bad."] },
  { serie: 'Narcos', alias: [], info: 'Netflix, depuis 2015',
    textes: ["Récit semi-documentaire, narré par un agent de la DEA, sur la traque d'un cartel colombien dans les années 80.",
             "L'ascension et la chute de Pablo Escobar à Medellín."] },
  { serie: 'How I Met Your Mother', alias: ['himym'], info: 'CBS, 2005-2014',
    textes: ["Un père raconte à ses enfants, pendant neuf saisons, la longue histoire qui l'a mené à leur mère.",
             "Ted, Marshall, Lily, Robin et un dragueur en costume nommé Barney, dans un bar new-yorkais."] },
  { serie: 'The Big Bang Theory', alias: ['big bang theory'], info: 'CBS, 2007-2019',
    textes: ["Des physiciens surdiplômés et socialement inadaptés voient une serveuse aspirante actrice emménager en face.",
             "Sheldon Cooper, sa place attitrée sur le canapé, et sa façon de frapper trois fois à la porte."] },
  { serie: 'Kaamelott', alias: [], info: 'M6, 2005-2009',
    textes: ["La légende arthurienne en épisodes de quelques minutes, où le roi est surtout entouré d'incapables.",
             "Perceval, Karadoc, le Roi Burgonde et un Arthur épuisé : la série d'Alexandre Astier."] },
  { serie: 'Engrenages', alias: ['spiral'], info: 'Canal+, 2005-2020',
    textes: ["Police judiciaire, juges d'instruction et avocats parisiens filmés au plus près de la procédure réelle.",
             "Le polar français de Canal+ centré sur le capitaine Laure Berthaud."] },
  { serie: 'Le Bureau des légendes', alias: ['bureau des legendes'], info: 'Canal+, 2015-2020',
    textes: ["Des agents clandestins de la DGSE vivent des années sous une fausse identité, jusqu'à s'y perdre.",
             "La série d'espionnage française d'Éric Rochant, avec Mathieu Kassovitz en agent « Malotru »."] },
  { serie: 'Dix pour cent', alias: ['10 pour cent', 'call my agent'], info: 'France 2, 2015-2020',
    textes: ["Dans une agence artistique parisienne, chaque épisode accueille une vraie vedette qui joue son propre rôle en pire.",
             "Andréa, Mathias, Gabriel et Arlette gèrent les caprices des stars du cinéma français."] },
  { serie: 'Un village français', alias: [], info: 'France 3, 2009-2017',
    textes: ["Sur sept saisons, une commune du Jura traverse l'Occupation : collaboration, résistance, épuration.",
             "La fresque française sur la vie quotidienne d'un village sous l'occupation allemande."] },
  { serie: 'Les Revenants', alias: [], info: 'Canal+, 2012-2015',
    textes: ["Dans une bourgade de montagne, des personnes mortes depuis des années rentrent chez elles sans avoir vieilli.",
             "La série fantastique française sur un barrage, un lac et des morts qui reviennent."] },
  { serie: 'Lupin', alias: [], info: 'Netflix, depuis 2021',
    textes: ["Un homme s'inspire des méthodes d'un personnage de romans du début du XXe siècle pour venger son père.",
             "Omar Sy en gentleman cambrioleur moderne, avec un casse au Louvre en ouverture."] },
  { serie: 'Prison Break', alias: [], info: 'Fox, 2005-2017',
    textes: ["Un ingénieur se fait volontairement incarcérer, tout le plan d'évasion tatoué sur le corps.",
             "Michael Scofield veut faire évader son frère du couloir de la mort de Fox River."] },
  { serie: 'Docteur House', alias: ['house', 'house md', 'dr house'], info: 'Fox, 2004-2012',
    textes: ["Un diagnosticien boiteux, accro aux antidouleurs, résout des cas impossibles en insultant tout le monde.",
             "« Ce n'est jamais un lupus » : la série médicale avec Hugh Laurie."] },
  { serie: 'Grey\'s Anatomy', alias: ['greys anatomy'], info: 'ABC, depuis 2005',
    textes: ["Série médicale-fleuve : catastrophes à répétition, internes devenus chefs, et un hôpital qui change plusieurs fois de nom.",
             "Meredith Grey et le Seattle Grace Hospital, depuis 2005."] },
  { serie: 'Les Soprano', alias: ['the sopranos', 'sopranos'], info: 'HBO, 1999-2007',
    textes: ["Un chef mafieux du New Jersey consulte une psychiatre pour ses crises d'angoisse — et sa fin en fondu au noir divise encore.",
             "Tony, ses crises d'angoisse, sa psy et sa Famille du New Jersey."] },
  { serie: 'The Wire', alias: ['sur ecoute'], info: 'HBO, 2002-2008',
    textes: ["Chaque saison change d'angle — les docks, la mairie, l'école, la presse — pour disséquer une ville entière.",
             "La série de Baltimore sur le trafic de drogue et les écoutes policières, souvent citée comme la meilleure jamais faite."] },
  { serie: 'Mad Men', alias: [], info: 'AMC, 2007-2015',
    textes: ["Publicitaires de Madison Avenue dans les années 60 : whisky au bureau, cigarettes en réunion, et un héros à l'identité volée.",
             "Don Draper et son agence de publicité new-yorkaise."] },
  { serie: 'Vikings', alias: [], info: 'History, 2013-2020',
    textes: ["Un fermier scandinave conteste son chef et met le cap à l'ouest, vers des monastères sans défense.",
             "Ragnar Lothbrok, Lagertha et les raids nordiques sur l'Angleterre."] },
  { serie: 'The Last of Us', alias: [], info: 'HBO, depuis 2023',
    textes: ["Adaptation d'un jeu vidéo saluée pour sa fidélité, où un champignon parasite a remplacé le virus habituel.",
             "Joel escorte Ellie à travers une Amérique ravagée par les infectés au cordyceps."] },
  { serie: 'Arcane', alias: [], info: 'Netflix, depuis 2021',
    textes: ["Série animée tirée d'un jeu compétitif, saluée pour son style peint à la main et deux sœurs que tout sépare.",
             "Vi et Jinx, Piltover et Zaun : l'adaptation animée de League of Legends."] },
  { serie: 'Rick et Morty', alias: ['rick and morty'], info: 'Adult Swim, depuis 2013',
    textes: ["Un savant alcoolique traîne son petit-fils angoissé de dimension en dimension, à coups de pistolet à portails.",
             "La série animée où un grand-père génial et cynique entraîne Morty dans le multivers."] },
  { serie: 'Les Simpson', alias: ['the simpsons', 'simpson'], info: 'Fox, depuis 1989',
    textes: ["Née de courts métrages dans une émission comique, elle est devenue la série d'animation la plus longue de l'histoire.",
             "Springfield, la centrale nucléaire et une famille jaune de cinq personnes."] },
  { serie: 'South Park', alias: [], info: 'Comedy Central, depuis 1997',
    textes: ["Fabriquée en quelques jours pour coller à l'actualité, avec un style de papiers découpés assumé.",
             "Quatre gamins mal élevés du Colorado : Stan, Kyle, Cartman et Kenny."] },
  { serie: 'Sex Education', alias: [], info: 'Netflix, 2019-2023',
    textes: ["Le fils d'une sexothérapeute monte une consultation clandestine dans les toilettes de son lycée.",
             "Otis, Maeve et Eric dans un lycée britannique aux couleurs très américaines."] },
  { serie: 'Ted Lasso', alias: [], info: 'Apple TV+, 2020-2023',
    textes: ["Né d'un sketch publicitaire, ce personnage d'entraîneur optimiste est devenu une série récompensée aux Emmy.",
             "Un coach de football américain débarque pour entraîner un club de Premier League sans rien y connaître."] },
  { serie: 'Succession', alias: [], info: 'HBO, 2018-2023',
    textes: ["Quatre héritiers se déchirent autour d'un patriarche vieillissant qui ne lâche jamais vraiment les rênes de son empire médiatique.",
             "La famille Roy, ses jets privés et ses trahisons à répétition."] },
  { serie: 'Malcolm', alias: ['malcolm in the middle'], info: 'Fox, 2000-2006',
    textes: ["Un enfant surdoué s'adresse à la caméra pour commenter le chaos permanent de sa famille et de ses frères.",
             "Hal, Lois, Francis, Reese et Dewey : la sitcom sans rires enregistrés des années 2000."] },
  { serie: 'X-Files', alias: ['aux frontieres du reel'], info: 'Fox, 1993-2018',
    textes: ["Deux agents fédéraux enquêtent sur des affaires classées inexplicables : l'un croit tout, l'autre ne croit rien.",
             "Mulder et Scully, et la vérité qui est ailleurs."] },
];
