/**
 * Blind Texte — banque « Philosophie » : retrouver le penseur.
 *
 * Deux régimes, choisis délibérément :
 *  - Auteurs du DOMAINE PUBLIC (l'immense majorité ici) : citation authentique courte,
 *    entre guillemets, avec l'œuvre en révélation.
 *  - Penseurs récents (œuvres encore protégées) : leur idée est DÉCRITE dans nos mots
 *    (concept, thèse, contexte) — jamais citée mot à mot.
 *
 * Format : { auteur, alias[], info (époque/œuvre, affichée au reveal), textes[2] }
 * textes[0] = difficile, textes[1] = facile.
 */

export const BANQUE_PHILO = [
  { auteur: 'René Descartes', alias: ['descartes'], info: 'Discours de la méthode, 1637',
    textes: ["Ce mathématicien français fonde toute certitude sur une seule évidence première, découverte en doutant de tout.",
             "« Je pense, donc je suis » : qui l'a écrit ?"] },
  { auteur: 'Socrate', alias: [], info: 'Athènes, Ve siècle av. J.-C.',
    textes: ["Il n'a pas écrit une ligne : on le connaît par ses disciples. Condamné à boire la ciguë pour avoir « corrompu la jeunesse ».",
             "« Je sais que je ne sais rien » : quel philosophe athénien, maître de Platon ?"] },
  { auteur: 'Platon', alias: [], info: 'La République, IVe siècle av. J.-C.',
    textes: ["Fondateur de l'Académie, il imagine des prisonniers enchaînés qui prennent des ombres projetées pour la réalité.",
             "L'allégorie de la caverne, le monde des Idées : quel disciple de Socrate ?"] },
  { auteur: 'Aristote', alias: [], info: 'Les Politiques, IVe siècle av. J.-C.',
    textes: ["Précepteur d'Alexandre le Grand, il classe tout : les animaux, les régimes politiques, les syllogismes.",
             "« L'homme est un animal politique » : quel élève de Platon, fondateur du Lycée ?"] },
  { auteur: 'Blaise Pascal', alias: ['pascal'], info: 'Pensées, 1670',
    textes: ["Génie précoce, il invente une machine à calculer, puis parie que croire en Dieu est le choix le plus rationnel.",
             "« Le cœur a ses raisons que la raison ne connaît point » : quel savant janséniste ?"] },
  { auteur: 'Friedrich Nietzsche', alias: ['nietzsche'], info: 'Le Gai Savoir, 1882',
    textes: ["Ce philologue allemand philosophe « au marteau » et proclame l'avènement du surhomme.",
             "« Dieu est mort » : quel moustachu, auteur d'Ainsi parlait Zarathoustra ?"] },
  { auteur: 'Emmanuel Kant', alias: ['kant'], info: 'Critique de la raison pratique, 1788',
    textes: ["Si ponctuel que les habitants de Königsberg réglaient, dit-on, leurs montres sur sa promenade quotidienne.",
             "« Le ciel étoilé au-dessus de moi et la loi morale en moi » : quel auteur de l'impératif catégorique ?"] },
  { auteur: 'Jean-Jacques Rousseau', alias: ['rousseau'], info: 'Du contrat social, 1762',
    textes: ["Citoyen de Genève, il voit dans la société la source de la corruption d'une nature humaine originellement bonne.",
             "« L'homme est né libre, et partout il est dans les fers » : quel philosophe des Lumières ?"] },
  { auteur: 'Karl Marx', alias: ['marx'], info: 'Critique de la philosophie du droit de Hegel, 1844',
    textes: ["Exilé à Londres, il passe ses journées à la bibliothèque du British Museum à disséquer le Capital.",
             "« La religion est l'opium du peuple » : quel barbu, compagnon d'Engels ?"] },
  { auteur: 'Thomas Hobbes', alias: ['hobbes'], info: 'Le Léviathan, 1651 (formule héritée de Plaute)',
    textes: ["Pour ce penseur anglais, seul un État tout-puissant — un monstre biblique — peut mettre fin à la guerre de tous contre tous.",
             "« L'homme est un loup pour l'homme » : quel théoricien du Léviathan a popularisé cette formule ?"] },
  { auteur: 'Michel de Montaigne', alias: ['montaigne'], info: 'Essais, 1580',
    textes: ["Retiré dans sa tour girondine, il invente un genre littéraire en se prenant lui-même pour sujet d'étude.",
             "« Que sais-je ? » : quel ami de La Boétie, maire de Bordeaux ?"] },
  { auteur: 'Voltaire', alias: ['francois-marie arouet', 'arouet'], info: 'Candide, 1759',
    textes: ["Embastillé deux fois, exilé en Angleterre, il combat « l'Infâme » à coups de contes et de pamphlets.",
             "« Il faut cultiver notre jardin » : quel patriarche de Ferney fait dire cela à Candide ?"] },
  { auteur: 'Baruch Spinoza', alias: ['spinoza'], info: "L'Éthique, 1677",
    textes: ["Excommunié de sa communauté d'Amsterdam, ce polisseur de lentilles démontre sa philosophie « à la manière des géomètres ».",
             "Dieu ou la Nature — Deus sive Natura : quel philosophe hollandais du XVIIe siècle ?"] },
  { auteur: 'Épicure', alias: ['epicure'], info: 'Lettre à Ménécée, IIIe siècle av. J.-C.',
    textes: ["Son école s'appelait le Jardin et, contrairement à sa réputation, on y prônait des plaisirs simples et mesurés.",
             "« La mort n'est rien pour nous » : quel Grec, dont le nom évoque à tort la bonne chère ?"] },
  { auteur: 'Marc Aurèle', alias: ['marc aurele'], info: 'Pensées pour moi-même, IIe siècle',
    textes: ["Il gouverne l'Empire romain le jour et rédige la nuit, pour lui seul, un manuel de sagesse stoïcienne.",
             "L'empereur-philosophe stoïcien, dont la mort ouvre le film Gladiator : qui est-il ?"] },
  { auteur: 'Sénèque', alias: ['seneque'], info: 'De la brièveté de la vie, Ier siècle',
    textes: ["Précepteur puis victime de Néron, ce stoïcien richissime écrit que la vie n'est pas courte : c'est nous qui la gaspillons.",
             "Contraint au suicide par son ancien élève Néron : quel stoïcien romain ?"] },
  { auteur: 'Héraclite', alias: ['heraclite'], info: 'Fragments, VIe siècle av. J.-C.',
    textes: ["Surnommé l'Obscur, ce présocratique d'Éphèse fait du feu et du devenir le principe de toute chose.",
             "« On ne se baigne jamais deux fois dans le même fleuve » : quel présocratique ?"] },
  { auteur: 'Protagoras', alias: [], info: 'Ve siècle av. J.-C.',
    textes: ["Le plus célèbre des sophistes, adversaire de Socrate, vendait fort cher ses leçons de rhétorique.",
             "« L'homme est la mesure de toute chose » : quel sophiste grec ?"] },
  { auteur: 'Diogène', alias: ['diogene de sinope', 'diogene le cynique'], info: 'IVe siècle av. J.-C.',
    textes: ["Il vivait dans une jarre, cherchait « un homme » en plein jour avec une lanterne, et se disait citoyen du monde.",
             "À Alexandre qui lui offrait n'importe quelle faveur, il demanda seulement de s'ôter de son soleil : qui ?"] },
  { auteur: 'Arthur Schopenhauer', alias: ['schopenhauer'], info: 'Le Monde comme volonté et comme représentation, 1818',
    textes: ["Ce pessimiste allemand, grand lecteur des sagesses indiennes, voyait l'existence osciller entre souffrance et ennui.",
             "Le philosophe du pessimisme, du vouloir-vivre aveugle et de la consolation par l'art : qui ?"] },
  { auteur: 'Søren Kierkegaard', alias: ['kierkegaard', 'soren kierkegaard'], info: 'Copenhague, XIXe siècle',
    textes: ["Ce Danois mélancolique rompt ses fiançailles avec Régine et publie sous une nuée de pseudonymes.",
             "Père de l'existentialisme chrétien, penseur de l'angoisse et du « saut » de la foi : qui ?"] },
  { auteur: 'Nicolas Machiavel', alias: ['machiavel'], info: 'Le Prince, 1532',
    textes: ["Diplomate florentin disgracié, il dédie aux Médicis un manuel de conquête et de conservation du pouvoir.",
             "Vaut-il mieux être craint qu'aimé ? Quel Florentin, dont le nom est devenu un adjectif peu flatteur ?"] },
  { auteur: 'Montesquieu', alias: ['charles de secondat'], info: "De l'esprit des lois, 1748",
    textes: ["Ce baron bordelais fait voyager deux Persans dans Paris pour mieux moquer les mœurs françaises.",
             "La séparation des pouvoirs — législatif, exécutif, judiciaire : quel penseur des Lumières l'a théorisée ?"] },
  { auteur: 'John Locke', alias: ['locke'], info: "Essai sur l'entendement humain, 1689",
    textes: ["Père du libéralisme politique, il fait de l'esprit à la naissance une page blanche que l'expérience remplit.",
             "La table rase, et les droits naturels — vie, liberté, propriété : quel Anglais ?"] },
  { auteur: 'David Hume', alias: ['hume'], info: "Enquête sur l'entendement humain, 1748",
    textes: ["Cet Écossais sceptique réveilla Kant de son « sommeil dogmatique » en doutant de la causalité même.",
             "Le soleil s'est toujours levé — mais rien ne garantit qu'il se lèvera demain : quel empiriste écossais ?"] },
  { auteur: 'Leibniz', alias: ['gottfried wilhelm leibniz'], info: 'Essais de théodicée, 1710',
    textes: ["Inventeur du calcul infinitésimal en même temps que Newton, il peuple l'univers de monades « sans portes ni fenêtres ».",
             "« Le meilleur des mondes possibles », que Voltaire ridiculisa dans Candide : quel Allemand l'a soutenu ?"] },
  { auteur: 'Hegel', alias: ['georg wilhelm friedrich hegel'], info: "Phénoménologie de l'esprit, 1807",
    textes: ["Il acheva son grand livre à Iéna en voyant passer Napoléon — « l'âme du monde » à cheval, écrivit-il.",
             "La dialectique du maître et de l'esclave, la ruse de la raison : quel idéaliste allemand ?"] },
  { auteur: 'Auguste Comte', alias: ['comte'], info: 'Cours de philosophie positive, 1830-1842',
    textes: ["Il rêva d'une « religion de l'Humanité » avec temples et calendrier, et inventa un mot en -logie promis à un grand avenir.",
             "Père du positivisme et de la sociologie, sa devise Ordre et Progrès figure sur le drapeau du Brésil : qui ?"] },
  { auteur: 'Henri Bergson', alias: ['bergson'], info: 'Le Rire, 1900',
    textes: ["Prix Nobel de littérature, ce Français oppose au temps des horloges la durée vécue de la conscience.",
             "L'élan vital, et le rire comme « du mécanique plaqué sur du vivant » : quel philosophe français ?"] },
  { auteur: 'Confucius', alias: ['kongzi', 'kong fuzi'], info: 'Entretiens, Ve siècle av. J.-C.',
    textes: ["Fonctionnaire déçu devenu maître itinérant, il fonde la morale sur les rites, la piété filiale et l'exemplarité.",
             "Ne pas faire à autrui ce qu'on ne voudrait pas subir soi-même : quel sage chinois a enseigné cette règle ?"] },
  { auteur: 'Lao Tseu', alias: ['laozi', 'lao tzu'], info: 'Tao Te King',
    textes: ["Figure peut-être légendaire, il aurait dicté son livre au gardien d'une passe avant de disparaître vers l'ouest.",
             "« Un voyage de mille lieues commence par un pas » ; le Tao et le non-agir : quel sage chinois ?"] },
  { auteur: 'Saint Augustin', alias: ['augustin', "augustin d'hippone"], info: 'Confessions, vers 400',
    textes: ["Fêtard converti, il raconte sa jeunesse dissolue — jusqu'à un vol de poires — dans la première autobiographie de l'histoire.",
             "« Aime, et fais ce que tu veux » : quel évêque d'Hippone, docteur de l'Église ?"] },
  { auteur: "Thomas d'Aquin", alias: ['saint thomas', 'thomas d aquin'], info: 'Somme théologique, XIIIe siècle',
    textes: ["Surnommé le « bœuf muet » par ses condisciples, ce dominicain massif réconcilie Aristote et le christianisme.",
             "Les cinq voies pour prouver l'existence de Dieu : quel « docteur angélique » du Moyen Âge ?"] },
  { auteur: 'Épictète', alias: ['epictete'], info: 'Manuel, IIe siècle',
    textes: ["Esclave affranchi devenu maître stoïcien, il enseigne à distinguer ce qui dépend de nous de ce qui n'en dépend pas.",
             "Un Manuel de stoïcisme enseigné par un ancien esclave boiteux : qui ?"] },
  { auteur: 'Pythagore', alias: [], info: 'VIe siècle av. J.-C.',
    textes: ["Sa communauté de Crotone, végétarienne, interdisait les fèves et voyait dans les nombres l'essence du monde.",
             "« Tout est nombre » — et un fameux théorème sur les triangles rectangles : quel Grec ?"] },
  { auteur: 'Sigmund Freud', alias: ['freud'], info: 'Introduction à la psychanalyse, 1917',
    textes: ["Ce Viennois amateur de cigares fait du rêve la « voie royale » vers un continent enfoui de l'esprit.",
             "Le moi n'est pas maître dans sa propre maison : quel inventeur de la psychanalyse ?"] },
  { auteur: 'Simone Weil', alias: ['weil'], info: "L'Enracinement, 1949",
    textes: ["Agrégée de philosophie, elle s'embauche comme ouvrière chez Renault pour penser la condition ouvrière de l'intérieur.",
             "Philosophe mystique de l'attention et de l'enracinement, morte d'épuisement à Londres en 1943 : qui ?"] },
  { auteur: 'Ludwig Wittgenstein', alias: ['wittgenstein'], info: 'Tractatus logico-philosophicus, 1921',
    textes: ["Héritier viennois richissime, il distribue sa fortune, devient instituteur de village, puis révolutionne deux fois la logique.",
             "« Ce dont on ne peut parler, il faut le taire » : quel logicien austro-britannique ?"] },
  { auteur: 'La Boétie', alias: ['etienne de la boetie'], info: 'Discours de la servitude volontaire, ~1548',
    textes: ["Mort à 32 ans, il inspira à son meilleur ami la plus belle définition de l'amitié : « Parce que c'était lui… ».",
             "Pourquoi des millions obéissent-ils à un seul, qui ne tient son pouvoir que d'eux ? Quel ami de Montaigne posa la question ?"] },
  // --- Penseurs récents : idées décrites, jamais citées mot à mot ---
  { auteur: 'Jean-Paul Sartre', alias: ['sartre'], info: "L'existentialisme est un humanisme, 1946",
    textes: ["Il refusa le prix Nobel de littérature en 1964 — une première dans l'histoire du prix.",
             "Chez lui, l'existence précède l'essence : rien ne nous définit d'avance, nous sommes ce que nous faisons. Quel compagnon de Simone de Beauvoir ?"] },
  { auteur: 'Albert Camus', alias: ['camus'], info: 'Le Mythe de Sisyphe, 1942',
    textes: ["Gardien de but en Algérie, prix Nobel à 44 ans, mort sur une route de l'Yonne trois ans plus tard.",
             "Face à l'absurde, il invite à imaginer heureux le damné qui roule éternellement son rocher : quel écrivain-philosophe ?"] },
  { auteur: 'Simone de Beauvoir', alias: ['beauvoir'], info: 'Le Deuxième Sexe, 1949',
    textes: ["Reçue à l'agrégation à 21 ans, juste derrière celui qui partagera toute sa vie sans jamais l'épouser.",
             "Pour elle, la féminité n'est pas un destin biologique : c'est la société qui la fabrique. Quelle pionnière du féminisme ?"] },
  { auteur: 'Hannah Arendt', alias: ['arendt'], info: 'Eichmann à Jérusalem, 1963',
    textes: ["Réfugiée allemande devenue américaine, elle couvre pour le New Yorker le procès d'un haut fonctionnaire nazi.",
             "Le mal peut être « banal » : commis sans haine, par simple renoncement à penser. Quelle philosophe l'a montré ?"] },
  { auteur: 'Michel Foucault', alias: ['foucault'], info: 'Surveiller et punir, 1975',
    textes: ["Crâne rasé, col roulé, il analyse la folie, la clinique, la prison — partout où le pouvoir façonne les corps.",
             "Une tour centrale d'où l'on peut être vu sans jamais voir : le panoptique comme symbole de la surveillance moderne. Quel Français ?"] },
  { auteur: 'John Rawls', alias: ['rawls'], info: 'Théorie de la justice, 1971',
    textes: ["Ce discret professeur de Harvard a relancé à lui seul la philosophie politique du XXe siècle.",
             "Choisir les règles de la société sans savoir qui l'on y sera : le « voile d'ignorance », c'est lui. Qui ?"] },
];
