/**
 * Blind Texte — banque « Géographie » : retrouver le lieu, le pays ou le monument.
 *
 * RÈGLE D'OR : un texte ne doit JAMAIS contenir sa propre réponse ni un alias.
 * Format : { reponse, alias[], info, textes[2] } — textes[0] difficile, [1] facile.
 */

export const BANQUE_GEO = [
  { reponse: 'Le Japon', alias: ['japon'], info: 'archipel de 14 000 îles',
    textes: ["Un archipel où l'on compte plus de cent volcans actifs, et dont la capitale a changé de nom en devenant capitale.",
             "Le pays du Soleil levant, de Tokyo, du mont Fuji et des cerisiers."] },
  { reponse: 'L\'Australie', alias: ['australie'], info: 'plus petit continent',
    textes: ["Seul pays à occuper un continent entier, avec une population concentrée sur les côtes et un centre quasi désertique.",
             "Le pays des kangourous, de la Grande Barrière de corail et de Sydney."] },
  { reponse: 'Le Canada', alias: ['canada'], info: '2ᵉ plus grand pays du monde',
    textes: ["Il possède plus de lacs que tous les autres pays réunis, et la plus longue frontière terrestre du monde avec un seul voisin.",
             "Le pays de la feuille d'érable, d'Ottawa et du Québec."] },
  { reponse: 'La Russie', alias: ['russie'], info: '11 fuseaux horaires',
    textes: ["Ce pays s'étend sur onze fuseaux horaires : quand il fait jour à un bout, il fait nuit à l'autre.",
             "Le plus vaste pays du monde, de Moscou à Vladivostok."] },
  { reponse: 'L\'Islande', alias: ['islande'], info: 'dorsale médio-atlantique',
    textes: ["Posée sur la limite entre deux plaques qui s'écartent, elle grandit de quelques centimètres par an et chauffe ses maisons à la géothermie.",
             "L'île volcanique du nord de l'Atlantique, avec Reykjavik et ses geysers."] },
  { reponse: 'Le Nil', alias: ['nil'], info: '6 650 km',
    textes: ["Ce fleuve traverse un désert sans recevoir d'affluent sur ses derniers 2 700 kilomètres, et il coule vers le nord.",
             "Le fleuve d'Égypte, longtemps considéré comme le plus long du monde."] },
  { reponse: 'L\'Amazone', alias: ['amazone', 'fleuve amazone'], info: 'Amérique du Sud',
    textes: ["Ce fleuve déverse à lui seul environ un cinquième de toute l'eau douce qui rejoint les océans.",
             "Le fleuve d'Amérique du Sud qui traverse la plus grande forêt tropicale du monde."] },
  { reponse: 'L\'Everest', alias: ['everest', 'mont everest'], info: '8 849 m',
    textes: ["Son altitude augmente encore de quelques millimètres par an, poussée par la collision de deux plaques continentales.",
             "Le plus haut sommet du monde, à la frontière du Népal et de la Chine."] },
  { reponse: 'Le Sahara', alias: ['sahara'], info: '9 millions de km²',
    textes: ["Il y a environ six mille ans, cette région était verte, parcourue de lacs et peuplée d'hippopotames — les peintures rupestres en témoignent.",
             "Le plus grand désert chaud du monde, en Afrique du Nord."] },
  { reponse: 'L\'Antarctique', alias: ['antarctique'], info: 'continent sans pays',
    textes: ["Techniquement le plus grand désert de la planète — il y tombe très peu de précipitations — et le seul continent sans population permanente.",
             "Le continent glacé du pôle Sud, avec ses manchots empereurs."] },
  { reponse: 'La Grande Barrière de corail', alias: ['grande barriere de corail', 'barriere de corail'], info: 'Australie, 2 300 km',
    textes: ["C'est la plus grande structure jamais bâtie par des êtres vivants, visible depuis l'espace, et elle blanchit à cause du réchauffement.",
             "L'immense récif corallien au large du Queensland australien."] },
  { reponse: 'Le Machu Picchu', alias: ['machu picchu'], info: 'Pérou, XVe siècle',
    textes: ["Cette cité de pierre à 2 430 mètres d'altitude n'a jamais été trouvée par les conquistadors ; elle fut révélée au monde en 1911.",
             "La cité inca perchée dans les Andes péruviennes."] },
  { reponse: 'Le Taj Mahal', alias: ['taj mahal'], info: 'Agra, Inde, 1653',
    textes: ["Un empereur l'a fait construire comme mausolée pour son épouse morte en couches ; le marbre change de teinte selon la lumière.",
             "Le monument de marbre blanc d'Agra, symbole de l'Inde."] },
  { reponse: 'La tour Eiffel', alias: ['tour eiffel'], info: 'Paris, 1889',
    textes: ["Conçue comme une structure temporaire pour une exposition universelle, elle devait être démontée après vingt ans — la radio l'a sauvée.",
             "Le monument de fer de 330 mètres qui domine Paris."] },
  { reponse: 'Le mont Saint-Michel', alias: ['mont saint michel'], info: 'Normandie',
    textes: ["Les marées y sont parmi les plus fortes d'Europe : la mer peut découvrir puis recouvrir plusieurs kilomètres de baie.",
             "L'abbaye sur son rocher entre Normandie et Bretagne."] },
  { reponse: 'Venise', alias: ['venise'], info: 'Italie, 118 îlots',
    textes: ["Bâtie sur des millions de pieux de bois enfoncés dans la vase, cette ville s'enfonce lentement et se protège par des digues mobiles.",
             "La cité italienne des canaux, des gondoles et du carnaval."] },
  { reponse: 'Le Colisée', alias: ['colisee'], info: 'Rome, 80 apr. J.-C.',
    textes: ["Cet amphithéâtre pouvait accueillir cinquante mille spectateurs et se vider en quelques minutes par ses quatre-vingts entrées numérotées.",
             "L'arène antique de Rome où combattaient les gladiateurs."] },
  { reponse: 'La Sagrada Família', alias: ['sagrada familia'], info: 'Barcelone, depuis 1882',
    textes: ["En chantier depuis plus de cent quarante ans, sa construction est financée uniquement par les dons et les entrées.",
             "La basilique inachevée de Gaudí à Barcelone."] },
  { reponse: 'Le Grand Canyon', alias: ['grand canyon'], info: 'Arizona, États-Unis',
    textes: ["Ses parois exposent près de deux milliards d'années d'histoire géologique, creusées par une rivière du Colorado.",
             "La gorge immense de l'Arizona, profonde de 1 800 mètres."] },
  { reponse: 'Les chutes du Niagara', alias: ['chutes du niagara', 'niagara'], info: 'frontière Canada-États-Unis',
    textes: ["Elles reculent de quelques centimètres par an en érodant la roche, et on les a déjà asséchées volontairement pour des travaux.",
             "Les cascades entre l'Ontario et l'État de New York."] },
  { reponse: 'Les chutes Victoria', alias: ['chutes victoria', 'victoria falls'], info: 'Zambie-Zimbabwe',
    textes: ["Leur nom local signifie « la fumée qui gronde », à cause de la brume visible à des dizaines de kilomètres.",
             "Les grandes chutes du Zambèze, en Afrique australe."] },
  { reponse: 'Le lac Baïkal', alias: ['baikal', 'lac baikal'], info: 'Sibérie',
    textes: ["Ce lac contient environ un cinquième de toute l'eau douce liquide non gelée de la planète, et atteint 1 642 mètres de profondeur.",
             "Le lac le plus profond du monde, en Sibérie, gelé une partie de l'année."] },
  { reponse: 'La mer Morte', alias: ['mer morte'], info: '-430 m sous le niveau de la mer',
    textes: ["Sa salinité est telle qu'aucun poisson n'y survit et qu'un corps humain y flotte sans effort ; son niveau baisse d'un mètre par an.",
             "Le point le plus bas des terres émergées, entre Israël et la Jordanie."] },
  { reponse: 'Les fjords de Norvège', alias: ['fjords', 'fjords de norvege', 'norvege'], info: 'Scandinavie',
    textes: ["Ces vallées glaciaires envahies par la mer découpent une côte dont la longueur dépasse celle de l'équateur.",
             "Les bras de mer encaissés du pays de Bergen et d'Oslo."] },
  { reponse: 'La Nouvelle-Zélande', alias: ['nouvelle zelande'], info: 'Océanie',
    textes: ["Ce pays a été le premier au monde à accorder le droit de vote aux femmes, en 1893, et compte cinq moutons par habitant.",
             "Le pays d'Auckland et de Wellington, décor du Seigneur des anneaux."] },
  { reponse: 'Le Groenland', alias: ['groenland'], info: 'territoire danois',
    textes: ["Sa calotte glaciaire fait par endroits trois kilomètres d'épaisseur, et son nom trompeur aurait servi d'argument de peuplement.",
             "La plus grande île du monde, autonome et rattachée au Danemark."] },
  { reponse: 'Le Vatican', alias: ['vatican', 'cite du vatican'], info: '0,44 km²',
    textes: ["Le plus petit État reconnu du monde, avec sa propre poste, sa garde suisse et aucune naissance sur son sol.",
             "L'enclave papale au cœur de Rome."] },
  { reponse: 'Monaco', alias: [], info: '2,08 km²',
    textes: ["Deuxième plus petit État du monde, il gagne du terrain sur la mer et accueille un Grand Prix dans ses rues.",
             "La principauté de la Côte d'Azur, avec son casino et son rocher."] },
  { reponse: 'Singapour', alias: ['singapour'], info: 'cité-État',
    textes: ["Cette cité-État tropicale a gagné plus de vingt pour cent de sa surface sur la mer, et importe presque toute son eau et sa nourriture.",
             "Le petit État d'Asie du Sud-Est au Marina Bay Sands."] },
  { reponse: 'Dubaï', alias: ['dubai'], info: 'Émirats arabes unis',
    textes: ["Cette ville abrite la plus haute tour du monde et des îles artificielles en forme de palmier visibles du ciel.",
             "La métropole des Émirats, avec la Burj Khalifa."] },
  { reponse: 'Istanbul', alias: ['istanbul'], info: 'Turquie',
    textes: ["Seule grande ville à cheval sur deux continents, elle a porté trois noms successifs et fut capitale de deux empires.",
             "La métropole turque du Bosphore, avec Sainte-Sophie."] },
  { reponse: 'Le canal de Suez', alias: ['canal de suez', 'suez'], info: 'Égypte, 1869',
    textes: ["Son blocage par un porte-conteneurs échoué en 2021 a paralysé environ dix pour cent du commerce mondial pendant six jours.",
             "Le canal égyptien qui relie la Méditerranée à la mer Rouge."] },
  { reponse: 'Le canal de Panama', alias: ['canal de panama', 'panama'], info: 'ouvert en 1914',
    textes: ["Sa construction a coûté la vie à des dizaines de milliers d'ouvriers, en grande partie à cause de la fièvre jaune et du paludisme.",
             "Le canal à écluses d'Amérique centrale entre l'Atlantique et le Pacifique."] },
  { reponse: 'Le détroit de Gibraltar', alias: ['gibraltar', 'detroit de gibraltar'], info: '14 km de large',
    textes: ["Quatorze kilomètres séparent ici deux continents ; la Méditerranée s'est déjà asséchée quand ce passage s'est refermé.",
             "Le passage entre l'Espagne et le Maroc, avec son rocher britannique."] },
  { reponse: 'La Loire', alias: ['loire'], info: '1 006 km',
    textes: ["Le plus long fleuve de son pays, réputé le dernier sauvage d'Europe occidentale, bordé de châteaux Renaissance.",
             "Le fleuve français d'Orléans, de Tours et de Chambord."] },
  { reponse: 'Le Mississippi', alias: ['mississippi'], info: 'États-Unis',
    textes: ["Ce fleuve draine environ 40 % du territoire de son pays et son delta avance dans le golfe du Mexique.",
             "Le grand fleuve américain de La Nouvelle-Orléans et des bateaux à aubes."] },
  { reponse: 'Le Danube', alias: ['danube'], info: '2 850 km, 10 pays',
    textes: ["Ce fleuve traverse ou borde dix pays et quatre capitales, plus que tout autre au monde.",
             "Le fleuve « bleu » qui passe par Vienne, Bratislava, Budapest et Belgrade."] },
  { reponse: 'Les Alpes', alias: ['alpes'], info: 'Europe, 1 200 km',
    textes: ["Cette chaîne est née de la collision entre l'Afrique et l'Europe, ce qui explique qu'on trouve des fossiles marins à son sommet.",
             "Le massif du mont Blanc, du Cervin et des stations de ski européennes."] },
  { reponse: 'L\'Himalaya', alias: ['himalaya'], info: 'Asie',
    textes: ["Cette chaîne abrite les quatorze sommets de plus de huit mille mètres de la planète, tous situés en Asie.",
             "La barrière montagneuse du Népal, du Tibet et du Bhoutan."] },
  { reponse: 'La cordillère des Andes', alias: ['andes', 'cordillere des andes'], info: '7 000 km',
    textes: ["La plus longue chaîne de montagnes émergée du monde, qui traverse sept pays du nord au sud d'un continent.",
             "Le relief qui longe toute la façade ouest de l'Amérique du Sud."] },
  { reponse: 'Le Kilimandjaro', alias: ['kilimandjaro'], info: 'Tanzanie, 5 895 m',
    textes: ["Volcan endormi situé à trois degrés de l'équateur, il porte pourtant des glaciers — qui fondent rapidement.",
             "Le plus haut sommet d'Afrique, en Tanzanie."] },
  { reponse: 'Le Brésil', alias: ['bresil'], info: 'Amérique du Sud',
    textes: ["Ce pays partage une frontière avec presque tous ses voisins continentaux — dix sur douze — et parle une langue différente d'eux tous.",
             "Le plus grand pays d'Amérique du Sud, avec Rio et Brasilia."] },
  { reponse: 'La Chine', alias: ['chine'], info: 'Asie de l\'Est',
    textes: ["Malgré son immense étendue est-ouest, ce pays fonctionne officiellement sur un seul fuseau horaire.",
             "Le pays de Pékin, de Shanghai et de la Grande Muraille."] },
  { reponse: 'L\'Inde', alias: ['inde'], info: 'Asie du Sud',
    textes: ["Devenu en 2023 le pays le plus peuplé du monde, il compte vingt-deux langues officielles et des centaines d'autres.",
             "Le pays de New Delhi, du Gange et de Bollywood."] },
  { reponse: 'L\'Égypte', alias: ['egypte'], info: 'Afrique du Nord',
    textes: ["Presque toute sa population vit sur environ cinq pour cent de son territoire, le long d'une bande verte au milieu du désert.",
             "Le pays du Caire, des pharaons et des pyramides."] },
  { reponse: 'La Grèce', alias: ['grece'], info: 'Europe du Sud',
    textes: ["Ce pays compte environ six mille îles et îlots, dont seulement deux cents sont habités.",
             "Le pays d'Athènes, de Santorin et de la mythologie antique."] },
  { reponse: 'Le Pérou', alias: ['perou'], info: 'Amérique du Sud',
    textes: ["On y trouve les sources du plus grand fleuve du monde, un désert côtier où il ne pleut presque jamais, et un lac navigable à 3 800 mètres.",
             "Le pays de Lima, du Machu Picchu et des lignes de Nazca."] },
  { reponse: 'Le Maroc', alias: ['maroc'], info: 'Afrique du Nord',
    textes: ["Ce pays possède à la fois des côtes atlantiques et méditerranéennes, une chaîne enneigée et une porte sur le grand désert.",
             "Le royaume de Rabat, Marrakech et Casablanca."] },
  { reponse: 'La Suisse', alias: ['suisse'], info: 'Europe centrale',
    textes: ["Ce pays sans accès à la mer a quatre langues officielles et n'a rejoint l'ONU qu'en 2002.",
             "Le pays de Berne, Genève, des banques et du chocolat."] },
  { reponse: 'L\'Espagne', alias: ['espagne'], info: 'péninsule Ibérique',
    textes: ["Deuxième pays du monde pour le nombre de sites classés au patrimoine mondial, il possède des villes autonomes sur un autre continent.",
             "Le pays de Madrid, Barcelone et de la paella."] },
  { reponse: 'L\'Italie', alias: ['italie'], info: 'Europe du Sud',
    textes: ["Sa forme de botte enferme deux États indépendants sur son territoire, et son volcan sicilien est le plus actif d'Europe.",
             "Le pays de Rome, de Florence et des pâtes."] },
  { reponse: 'Les Pays-Bas', alias: ['pays bas', 'hollande'], info: 'Europe du Nord-Ouest',
    textes: ["Environ un quart de ce pays se trouve sous le niveau de la mer, protégé par un système de digues et de polders.",
             "Le pays d'Amsterdam, des tulipes et des moulins."] },
  { reponse: 'La Corée du Sud', alias: ['coree du sud'], info: 'Asie de l\'Est',
    textes: ["Ce pays est passé en cinquante ans d'un des plus pauvres du monde à un géant technologique, et sa capitale concentre la moitié du pays.",
             "Le pays de Séoul, de la K-pop et de Samsung."] },
  { reponse: 'Le Mexique', alias: ['mexique'], info: 'Amérique du Nord',
    textes: ["Sa capitale, bâtie sur un ancien lac asséché, s'enfonce de plusieurs centimètres par an.",
             "Le pays des tacos, des mariachis et des pyramides mayas."] },
  { reponse: 'La Norvège', alias: ['norvege'], info: 'Scandinavie',
    textes: ["Au nord du cercle polaire, ce pays connaît des semaines entières sans coucher de soleil en été, et sans lever en hiver.",
             "Le pays du soleil de minuit, des fjords et d'Oslo."] },
];
