/**
 * ============================================================================
 *  BANQUE DE MOTS ET DE PHRASES DU PENDU
 * ============================================================================
 *
 *  Fichier de données pur (aucune logique de jeu) : modifiez-le librement.
 *
 *  AJOUTER UN MOT
 *  ----------------------------------------------------------------------
 *  Ajoutez une ligne dans le tableau MOTS : { texte: "GIRAFE", categorie: "Animaux" }
 *  - "texte" : en MAJUSCULES, un seul mot (pas d'espace).
 *  - "categorie" : sert uniquement au filtre du salon ; une nouvelle valeur
 *    crée automatiquement une nouvelle catégorie, sans autre modification.
 *
 *  AJOUTER UNE PHRASE
 *  ----------------------------------------------------------------------
 *  Ajoutez une ligne dans le tableau PHRASES : { texte: "L'UNION FAIT LA FORCE", categorie: "Proverbe" }
 *  - Les espaces, apostrophes et tirets sont affichés automatiquement (on ne
 *    les fait pas deviner) : seules les lettres comptent comme des essais.
 * ============================================================================
 */

export const MOTS = [
  // --- Animaux ---
  { texte: "CHAT", categorie: "Animaux" },
  { texte: "CHIEN", categorie: "Animaux" },
  { texte: "ELEPHANT", categorie: "Animaux" },
  { texte: "GIRAFE", categorie: "Animaux" },
  { texte: "TIGRE", categorie: "Animaux" },
  { texte: "LION", categorie: "Animaux" },
  { texte: "SINGE", categorie: "Animaux" },
  { texte: "DAUPHIN", categorie: "Animaux" },
  { texte: "BALEINE", categorie: "Animaux" },
  { texte: "KANGOUROU", categorie: "Animaux" },
  { texte: "ZEBRE", categorie: "Animaux" },
  { texte: "PANDA", categorie: "Animaux" },
  { texte: "OURS", categorie: "Animaux" },
  { texte: "LOUP", categorie: "Animaux" },
  { texte: "RENARD", categorie: "Animaux" },
  { texte: "HERISSON", categorie: "Animaux" },
  { texte: "ECUREUIL", categorie: "Animaux" },
  { texte: "PAPILLON", categorie: "Animaux" },
  { texte: "ABEILLE", categorie: "Animaux" },
  { texte: "FOURMI", categorie: "Animaux" },
  { texte: "TORTUE", categorie: "Animaux" },
  { texte: "SERPENT", categorie: "Animaux" },
  { texte: "CROCODILE", categorie: "Animaux" },
  { texte: "HIPPOPOTAME", categorie: "Animaux" },
  { texte: "RHINOCEROS", categorie: "Animaux" },
  { texte: "CHAMEAU", categorie: "Animaux" },
  { texte: "AUTRUCHE", categorie: "Animaux" },
  { texte: "PINGOUIN", categorie: "Animaux" },
  { texte: "PERROQUET", categorie: "Animaux" },
  { texte: "HIBOU", categorie: "Animaux" },
  { texte: "REQUIN", categorie: "Animaux" },
  { texte: "POULPE", categorie: "Animaux" },
  { texte: "MEDUSE", categorie: "Animaux" },
  { texte: "ESCARGOT", categorie: "Animaux" },
  { texte: "GRENOUILLE", categorie: "Animaux" },
  { texte: "LIBELLULE", categorie: "Animaux" },
  { texte: "COCCINELLE", categorie: "Animaux" },
  { texte: "ARAIGNEE", categorie: "Animaux" },

  // --- Métiers ---
  { texte: "BOULANGER", categorie: "Métiers" },
  { texte: "MEDECIN", categorie: "Métiers" },
  { texte: "INFIRMIER", categorie: "Métiers" },
  { texte: "PROFESSEUR", categorie: "Métiers" },
  { texte: "POMPIER", categorie: "Métiers" },
  { texte: "POLICIER", categorie: "Métiers" },
  { texte: "AVOCAT", categorie: "Métiers" },
  { texte: "INGENIEUR", categorie: "Métiers" },
  { texte: "ARCHITECTE", categorie: "Métiers" },
  { texte: "AGRICULTEUR", categorie: "Métiers" },
  { texte: "PECHEUR", categorie: "Métiers" },
  { texte: "BOUCHER", categorie: "Métiers" },
  { texte: "COIFFEUR", categorie: "Métiers" },
  { texte: "MECANICIEN", categorie: "Métiers" },
  { texte: "ELECTRICIEN", categorie: "Métiers" },
  { texte: "PLOMBIER", categorie: "Métiers" },
  { texte: "MENUISIER", categorie: "Métiers" },
  { texte: "JOURNALISTE", categorie: "Métiers" },
  { texte: "PHOTOGRAPHE", categorie: "Métiers" },
  { texte: "MUSICIEN", categorie: "Métiers" },
  { texte: "PEINTRE", categorie: "Métiers" },
  { texte: "SCULPTEUR", categorie: "Métiers" },
  { texte: "INFORMATICIEN", categorie: "Métiers" },
  { texte: "PILOTE", categorie: "Métiers" },
  { texte: "ASTRONAUTE", categorie: "Métiers" },
  { texte: "VETERINAIRE", categorie: "Métiers" },
  { texte: "DENTISTE", categorie: "Métiers" },
  { texte: "PHARMACIEN", categorie: "Métiers" },
  { texte: "CUISINIER", categorie: "Métiers" },
  { texte: "SERVEUR", categorie: "Métiers" },

  // --- Nourriture ---
  { texte: "FROMAGE", categorie: "Nourriture" },
  { texte: "BAGUETTE", categorie: "Nourriture" },
  { texte: "CROISSANT", categorie: "Nourriture" },
  { texte: "CHOCOLAT", categorie: "Nourriture" },
  { texte: "GATEAU", categorie: "Nourriture" },
  { texte: "TARTE", categorie: "Nourriture" },
  { texte: "SOUPE", categorie: "Nourriture" },
  { texte: "SALADE", categorie: "Nourriture" },
  { texte: "PIZZA", categorie: "Nourriture" },
  { texte: "RIZ", categorie: "Nourriture" },
  { texte: "POISSON", categorie: "Nourriture" },
  { texte: "POMME", categorie: "Nourriture" },
  { texte: "BANANE", categorie: "Nourriture" },
  { texte: "ORANGE", categorie: "Nourriture" },
  { texte: "FRAISE", categorie: "Nourriture" },
  { texte: "CERISE", categorie: "Nourriture" },
  { texte: "ANANAS", categorie: "Nourriture" },
  { texte: "CITRON", categorie: "Nourriture" },
  { texte: "CAROTTE", categorie: "Nourriture" },
  { texte: "TOMATE", categorie: "Nourriture" },
  { texte: "COURGETTE", categorie: "Nourriture" },
  { texte: "AUBERGINE", categorie: "Nourriture" },
  { texte: "CHAMPIGNON", categorie: "Nourriture" },
  { texte: "NOISETTE", categorie: "Nourriture" },
  { texte: "AMANDE", categorie: "Nourriture" },
  { texte: "FRAMBOISE", categorie: "Nourriture" },
  { texte: "PASTEQUE", categorie: "Nourriture" },
  { texte: "MANGUE", categorie: "Nourriture" },

  // --- Objets du quotidien ---
  { texte: "TELEVISION", categorie: "Objets" },
  { texte: "ORDINATEUR", categorie: "Objets" },
  { texte: "TELEPHONE", categorie: "Objets" },
  { texte: "REFRIGERATEUR", categorie: "Objets" },
  { texte: "ASPIRATEUR", categorie: "Objets" },
  { texte: "PARAPLUIE", categorie: "Objets" },
  { texte: "LUNETTES", categorie: "Objets" },
  { texte: "CHAISE", categorie: "Objets" },
  { texte: "TABLE", categorie: "Objets" },
  { texte: "LAMPE", categorie: "Objets" },
  { texte: "MIROIR", categorie: "Objets" },
  { texte: "HORLOGE", categorie: "Objets" },
  { texte: "VALISE", categorie: "Objets" },
  { texte: "CEINTURE", categorie: "Objets" },
  { texte: "CHAUSSURE", categorie: "Objets" },
  { texte: "CHAPEAU", categorie: "Objets" },
  { texte: "ECHARPE", categorie: "Objets" },
  { texte: "BROSSE", categorie: "Objets" },
  { texte: "PEIGNE", categorie: "Objets" },
  { texte: "SAVON", categorie: "Objets" },
  { texte: "SERVIETTE", categorie: "Objets" },
  { texte: "OREILLER", categorie: "Objets" },
  { texte: "COUVERTURE", categorie: "Objets" },
  { texte: "MATELAS", categorie: "Objets" },
  { texte: "FENETRE", categorie: "Objets" },
  { texte: "ESCALIER", categorie: "Objets" },
  { texte: "ASCENSEUR", categorie: "Objets" },
  { texte: "BALAI", categorie: "Objets" },

  // --- Nature ---
  { texte: "MONTAGNE", categorie: "Nature" },
  { texte: "RIVIERE", categorie: "Nature" },
  { texte: "OCEAN", categorie: "Nature" },
  { texte: "FORET", categorie: "Nature" },
  { texte: "DESERT", categorie: "Nature" },
  { texte: "VOLCAN", categorie: "Nature" },
  { texte: "CASCADE", categorie: "Nature" },
  { texte: "VALLEE", categorie: "Nature" },
  { texte: "PLAGE", categorie: "Nature" },
  { texte: "FALAISE", categorie: "Nature" },
  { texte: "GLACIER", categorie: "Nature" },
  { texte: "NUAGE", categorie: "Nature" },
  { texte: "ORAGE", categorie: "Nature" },
  { texte: "TEMPETE", categorie: "Nature" },
  { texte: "TORNADE", categorie: "Nature" },
  { texte: "ECLAIR", categorie: "Nature" },
  { texte: "TONNERRE", categorie: "Nature" },
  { texte: "BROUILLARD", categorie: "Nature" },
  { texte: "ROSEE", categorie: "Nature" },
  { texte: "ETOILE", categorie: "Nature" },
  { texte: "PLANETE", categorie: "Nature" },
  { texte: "COMETE", categorie: "Nature" },
  { texte: "GALAXIE", categorie: "Nature" },
  { texte: "ECLIPSE", categorie: "Nature" },
  { texte: "AURORE", categorie: "Nature" },

  // --- Sports ---
  { texte: "FOOTBALL", categorie: "Sports" },
  { texte: "BASKETBALL", categorie: "Sports" },
  { texte: "TENNIS", categorie: "Sports" },
  { texte: "NATATION", categorie: "Sports" },
  { texte: "CYCLISME", categorie: "Sports" },
  { texte: "ESCRIME", categorie: "Sports" },
  { texte: "JUDO", categorie: "Sports" },
  { texte: "KARATE", categorie: "Sports" },
  { texte: "BOXE", categorie: "Sports" },
  { texte: "RUGBY", categorie: "Sports" },
  { texte: "VOLLEYBALL", categorie: "Sports" },
  { texte: "HANDBALL", categorie: "Sports" },
  { texte: "ATHLETISME", categorie: "Sports" },
  { texte: "GYMNASTIQUE", categorie: "Sports" },
  { texte: "ESCALADE", categorie: "Sports" },
  { texte: "PLONGEE", categorie: "Sports" },
  { texte: "SURF", categorie: "Sports" },
  { texte: "PATINAGE", categorie: "Sports" },
  { texte: "VOILE", categorie: "Sports" },

  // --- Transports ---
  { texte: "VOITURE", categorie: "Transports" },
  { texte: "CAMION", categorie: "Transports" },
  { texte: "MOTO", categorie: "Transports" },
  { texte: "VELO", categorie: "Transports" },
  { texte: "TRAIN", categorie: "Transports" },
  { texte: "AVION", categorie: "Transports" },
  { texte: "BATEAU", categorie: "Transports" },
  { texte: "HELICOPTERE", categorie: "Transports" },
  { texte: "FUSEE", categorie: "Transports" },
  { texte: "TRAMWAY", categorie: "Transports" },
  { texte: "METRO", categorie: "Transports" },
  { texte: "SCOOTER", categorie: "Transports" },
  { texte: "SOUSMARIN", categorie: "Transports" },
  { texte: "MONTGOLFIERE", categorie: "Transports" },

  // --- Instruments de musique ---
  { texte: "PIANO", categorie: "Musique" },
  { texte: "GUITARE", categorie: "Musique" },
  { texte: "VIOLON", categorie: "Musique" },
  { texte: "BATTERIE", categorie: "Musique" },
  { texte: "TROMPETTE", categorie: "Musique" },
  { texte: "FLUTE", categorie: "Musique" },
  { texte: "SAXOPHONE", categorie: "Musique" },
  { texte: "HARPE", categorie: "Musique" },
  { texte: "ACCORDEON", categorie: "Musique" },
  { texte: "CLARINETTE", categorie: "Musique" },
  { texte: "TAMBOUR", categorie: "Musique" },
  { texte: "VIOLONCELLE", categorie: "Musique" },
  { texte: "XYLOPHONE", categorie: "Musique" },
  { texte: "TUBA", categorie: "Musique" },
  { texte: "BANJO", categorie: "Musique" },

  // --- Vêtements ---
  { texte: "PANTALON", categorie: "Vêtements" },
  { texte: "CHEMISE", categorie: "Vêtements" },
  { texte: "ROBE", categorie: "Vêtements" },
  { texte: "JUPE", categorie: "Vêtements" },
  { texte: "MANTEAU", categorie: "Vêtements" },
  { texte: "VESTE", categorie: "Vêtements" },
  { texte: "PULL", categorie: "Vêtements" },
  { texte: "CHAUSSETTE", categorie: "Vêtements" },
  { texte: "GILET", categorie: "Vêtements" },
  { texte: "COSTUME", categorie: "Vêtements" },
  { texte: "PYJAMA", categorie: "Vêtements" },
  { texte: "MAILLOT", categorie: "Vêtements" },
  { texte: "CASQUETTE", categorie: "Vêtements" },
  { texte: "FOULARD", categorie: "Vêtements" },

  // --- Émotions et adjectifs ---
  { texte: "JOYEUX", categorie: "Émotions" },
  { texte: "TRISTE", categorie: "Émotions" },
  { texte: "FURIEUX", categorie: "Émotions" },
  { texte: "TIMIDE", categorie: "Émotions" },
  { texte: "COURAGEUX", categorie: "Émotions" },
  { texte: "CURIEUX", categorie: "Émotions" },
  { texte: "JALOUX", categorie: "Émotions" },
  { texte: "FATIGUE", categorie: "Émotions" },
  { texte: "SURPRIS", categorie: "Émotions" },
  { texte: "INQUIET", categorie: "Émotions" },
  { texte: "FIER", categorie: "Émotions" },
  { texte: "GENEREUX", categorie: "Émotions" },
  { texte: "PATIENT", categorie: "Émotions" },
  { texte: "GOURMAND", categorie: "Émotions" },
  { texte: "PARESSEUX", categorie: "Émotions" },
];

export const PHRASES = [
  // --- Proverbes ---
  { texte: "PETIT A PETIT L'OISEAU FAIT SON NID", categorie: "Proverbe" },
  { texte: "IL NE FAUT PAS VENDRE LA PEAU DE L'OURS AVANT DE L'AVOIR TUE", categorie: "Proverbe" },
  { texte: "QUI VEUT VOYAGER LOIN MENAGE SA MONTURE", categorie: "Proverbe" },
  { texte: "L'HABIT NE FAIT PAS LE MOINE", categorie: "Proverbe" },
  { texte: "APRES LA PLUIE LE BEAU TEMPS", categorie: "Proverbe" },
  { texte: "CHAT ECHAUDE CRAINT L'EAU FROIDE", categorie: "Proverbe" },
  { texte: "IL FAUT BATTRE LE FER PENDANT QU'IL EST CHAUD", categorie: "Proverbe" },
  { texte: "LES PETITS RUISSEAUX FONT LES GRANDES RIVIERES", categorie: "Proverbe" },
  { texte: "PIERRE QUI ROULE N'AMASSE PAS MOUSSE", categorie: "Proverbe" },
  { texte: "QUI SEME LE VENT RECOLTE LA TEMPETE", categorie: "Proverbe" },
  { texte: "MIEUX VAUT TARD QUE JAMAIS", categorie: "Proverbe" },
  { texte: "TOUT VIENT A POINT A QUI SAIT ATTENDRE", categorie: "Proverbe" },
  { texte: "LOIN DES YEUX LOIN DU COEUR", categorie: "Proverbe" },
  { texte: "QUI NE RISQUE RIEN N'A RIEN", categorie: "Proverbe" },
  { texte: "L'ARGENT NE FAIT PAS LE BONHEUR", categorie: "Proverbe" },
  { texte: "UN TIENS VAUT MIEUX QUE DEUX TU L'AURAS", categorie: "Proverbe" },
  { texte: "IL N'Y A PAS DE FUMEE SANS FEU", categorie: "Proverbe" },
  { texte: "LES BONS COMPTES FONT LES BONS AMIS", categorie: "Proverbe" },
  { texte: "QUI VOLE UN OEUF VOLE UN BOEUF", categorie: "Proverbe" },
  { texte: "CHACUN VOIT MIDI A SA PORTE", categorie: "Proverbe" },
  { texte: "IL FAUT TOURNER SEPT FOIS SA LANGUE DANS SA BOUCHE", categorie: "Proverbe" },
  { texte: "RIEN NE SERT DE COURIR IL FAUT PARTIR A POINT", categorie: "Proverbe" },
  { texte: "LES MURS ONT DES OREILLES", categorie: "Proverbe" },
  { texte: "QUAND LE CHAT N'EST PAS LA LES SOURIS DANSENT", categorie: "Proverbe" },
  { texte: "IL NE FAUT PAS METTRE TOUS SES OEUFS DANS LE MEME PANIER", categorie: "Proverbe" },
  { texte: "TOUS LES CHEMINS MENENT A ROME", categorie: "Proverbe" },
  { texte: "A COEUR VAILLANT RIEN D'IMPOSSIBLE", categorie: "Proverbe" },
  { texte: "AIDE TOI LE CIEL T'AIDERA", categorie: "Proverbe" },
  { texte: "IMPOSSIBLE N'EST PAS FRANCAIS", categorie: "Proverbe" },
  { texte: "LA NUIT PORTE CONSEIL", categorie: "Proverbe" },
  { texte: "QUI DORT DINE", categorie: "Proverbe" },
  { texte: "L'UNION FAIT LA FORCE", categorie: "Proverbe" },
  { texte: "VOULOIR C'EST POUVOIR", categorie: "Proverbe" },
  { texte: "QUI SE RESSEMBLE S'ASSEMBLE", categorie: "Proverbe" },
  { texte: "LE TEMPS C'EST DE L'ARGENT", categorie: "Proverbe" },
  { texte: "PETIT POISSON DEVIENDRA GRAND", categorie: "Proverbe" },
  { texte: "IL FAUT SE MEFIER DE L'EAU QUI DORT", categorie: "Proverbe" },
  { texte: "MIEUX VAUT PREVENIR QUE GUERIR", categorie: "Proverbe" },
  { texte: "TEL EST PRIS QUI CROYAIT PRENDRE", categorie: "Proverbe" },
  { texte: "CHACUN SON GOUT", categorie: "Proverbe" },

  // --- Expressions ---
  { texte: "AVOIR LE COEUR SUR LA MAIN", categorie: "Expression" },
  { texte: "POSER UN LAPIN", categorie: "Expression" },
  { texte: "TOMBER DANS LES POMMES", categorie: "Expression" },
  { texte: "AVOIR UN CHAT DANS LA GORGE", categorie: "Expression" },
  { texte: "COUTER LES YEUX DE LA TETE", categorie: "Expression" },
  { texte: "AVOIR LE CAFARD", categorie: "Expression" },
  { texte: "PRENDRE SES JAMBES A SON COU", categorie: "Expression" },
  { texte: "AVOIR LA TETE DANS LES NUAGES", categorie: "Expression" },
  { texte: "METTRE LA CHARRUE AVANT LES BOEUFS", categorie: "Expression" },
  { texte: "AVOIR UNE FAIM DE LOUP", categorie: "Expression" },
  { texte: "APPELER UN CHAT UN CHAT", categorie: "Expression" },
  { texte: "DONNER SA LANGUE AU CHAT", categorie: "Expression" },
  { texte: "AVOIR LE BEURRE ET L'ARGENT DU BEURRE", categorie: "Expression" },
  { texte: "REVENONS A NOS MOUTONS", categorie: "Expression" },
  { texte: "CASSER DU SUCRE SUR LE DOS DE QUELQU'UN", categorie: "Expression" },
  { texte: "AVOIR UN POIL DANS LA MAIN", categorie: "Expression" },
  { texte: "FAIRE LA GRASSE MATINEE", categorie: "Expression" },
  { texte: "TIRER LES VERS DU NEZ", categorie: "Expression" },
  { texte: "METTRE LES PIEDS DANS LE PLAT", categorie: "Expression" },
  { texte: "PASSER UNE NUIT BLANCHE", categorie: "Expression" },
  { texte: "AVOIR LA MAIN VERTE", categorie: "Expression" },
  { texte: "TOMBER DE HAUT", categorie: "Expression" },
  { texte: "ETRE DANS LA LUNE", categorie: "Expression" },
  { texte: "AVOIR DES FOURMIS DANS LES JAMBES", categorie: "Expression" },
  { texte: "FAIRE D'UNE PIERRE DEUX COUPS", categorie: "Expression" },
  { texte: "AVOIR UN OEIL DE LYNX", categorie: "Expression" },
  { texte: "CHERCHER MIDI A QUATORZE HEURES", categorie: "Expression" },
  { texte: "METTRE SON GRAIN DE SEL", categorie: "Expression" },
  { texte: "AVOIR LES YEUX PLUS GROS QUE LE VENTRE", categorie: "Expression" },
  { texte: "COMME UN POISSON DANS L'EAU", categorie: "Expression" },
  { texte: "AVOIR LE VENT EN POUPE", categorie: "Expression" },
  { texte: "METTRE LA MAIN A LA PATE", categorie: "Expression" },
  { texte: "AVOIR DU PAIN SUR LA PLANCHE", categorie: "Expression" },
  { texte: "NE PAS Y ALLER PAR QUATRE CHEMINS", categorie: "Expression" },
  { texte: "AVOIR LA PECHE", categorie: "Expression" },
  { texte: "FAIRE LA SOURDE OREILLE", categorie: "Expression" },
  { texte: "PARLER FRANCAIS COMME UNE VACHE ESPAGNOLE", categorie: "Expression" },
  { texte: "TOURNER AUTOUR DU POT", categorie: "Expression" },
  { texte: "AVOIR LA GROSSE TETE", categorie: "Expression" },
  { texte: "METTRE DE L'EAU DANS SON VIN", categorie: "Expression" },
  { texte: "AVOIR LE MORAL DANS LES CHAUSSETTES", categorie: "Expression" },
  { texte: "PASSER DU COQ A L'ANE", categorie: "Expression" },
  { texte: "AVOIR UN COEUR D'ARTICHAUT", categorie: "Expression" },
  { texte: "FAIRE LE PONT", categorie: "Expression" },
  { texte: "AVOIR LE BRAS LONG", categorie: "Expression" },
  { texte: "SE SERRER LES COUDES", categorie: "Expression" },
  { texte: "AVOIR LES DENTS QUI RAYENT LE PARQUET", categorie: "Expression" },
  { texte: "REGARDER LES ETOILES", categorie: "Expression" },

  // --- Titres de films et dessins animés ---
  { texte: "LE ROI LION", categorie: "Titre" },
  { texte: "LA REINE DES NEIGES", categorie: "Titre" },
  { texte: "TOY STORY", categorie: "Titre" },
  { texte: "LE SEIGNEUR DES ANNEAUX", categorie: "Titre" },
  { texte: "HARRY POTTER", categorie: "Titre" },
  { texte: "STAR WARS", categorie: "Titre" },
  { texte: "JURASSIC PARK", categorie: "Titre" },
  { texte: "TITANIC", categorie: "Titre" },
  { texte: "LES DENTS DE LA MER", categorie: "Titre" },
  { texte: "RETOUR VERS LE FUTUR", categorie: "Titre" },
  { texte: "LE VOYAGE DE CHIHIRO", categorie: "Titre" },
  { texte: "LE FABULEUX DESTIN D'AMELIE POULAIN", categorie: "Titre" },
  { texte: "INTOUCHABLES", categorie: "Titre" },
  { texte: "LE GRAND BLEU", categorie: "Titre" },
  { texte: "LA VIE EST BELLE", categorie: "Titre" },
  { texte: "SHREK", categorie: "Titre" },
  { texte: "MADAGASCAR", categorie: "Titre" },
  { texte: "LES INDESTRUCTIBLES", categorie: "Titre" },
  { texte: "MONSTRES ET CIE", categorie: "Titre" },
  { texte: "LE MONDE DE NEMO", categorie: "Titre" },
  { texte: "LA BELLE ET LA BETE", categorie: "Titre" },
  { texte: "BLANCHE NEIGE", categorie: "Titre" },
  { texte: "ALADDIN", categorie: "Titre" },
  { texte: "LA PETITE SIRENE", categorie: "Titre" },
  { texte: "PIRATES DES CARAIBES", categorie: "Titre" },
  { texte: "MISSION IMPOSSIBLE", categorie: "Titre" },
  { texte: "KUNG FU PANDA", categorie: "Titre" },
  { texte: "COCO", categorie: "Titre" },
];
